// src/OpenFPL_frontend/src/components/whitepaper/dao.jsx
import React from 'react';

const DAO = () => {
  
  return (
    <div className="w-100 px-3">

        <h3 className='mb-4'>OpenFPL DAO</h3>
        
        <h5>Operating Framework</h5>
        <p className='mb-4'>OpenFPL functions entirely on-chain as a DAO, aspiring to operate under the Internet Computer’s Service Nervous System. 
            The DAO is structured to run in parallel with the Premier League season, relying on input from its neuron holders who are rewarded for maintaining independence from third-party services.</p>
        
        <h5>DAO Reward Structure</h5>

        <p>The DAO incentivizes participation through monthly minting of new FPL tokens, calculated annually as 2.5% of the total $FPL supply as of August 1st. These tokens are allocated to:</p>
        <ul className='mb-4'>
            <li>Gameplay Rewards (75%)</li>
            <li>Governance Rewards (25%)</li>
        </ul>

        <h5>Gameplay Rewards (75%)</h5>

        <p>The DAO is designed to reward users for their expertise in fantasy football, with rewards distributed weekly, monthly, and annually based on performance. 
            The rewards are tiered to encourage ongoing engagement. Here’s the breakdown:</p>

        <ul>
            <li>Global Season Leaderboard Rewards: 30% for the top 100 global season positions.</li>
            <li>Club Monthly Leaderboard Rewards: 20% for the top 100 in each monthly club leaderboard, adjusted for the number of fans in each club.</li>
            <li>Global Weekly Leaderboard Rewards: 15% for the top 100 weekly positions.</li>
            <li>Most Valuable Team Rewards: 10% for the top 100 most valuable teams at season's end.</li>
            <li>Highest Scoring Match Player Rewards: 10% split among managers selecting the highest-scoring player in a fixture.</li>
            <li>Weekly/Monthly/Season ATH Score Rewards: 5% each, reserved for breaking all-time high scores in respective categories.</li>
        </ul>       

        <p>A user is rewarded for their leaderboard position across the top 100 positions. The following is a breakdown of the reward share for each position:</p>

        <table>
            <tr>
                <th>Pos</th>
                <th>Share</th>
                <th>Pos</th>
                <th>Share</th>
                <th>Pos</th>
                <th>Share</th>
                <th>Pos</th>
                <th>Share</th>
            </tr>

            <tr>
                <td>1</td>
                <td>36.09%</td>
                <td>26</td>
                <td>0.391%</td>
                <td>51</td>
                <td>0.0662%</td>
                <td>76</td>
                <td>0.012%</td>
            </tr>

            <tr>
                <td>2</td>
                <td>18.91%</td>
                <td>27</td>
                <td>0.365%</td>
                <td>52</td>
                <td>0.0627%</td>
                <td>77</td>
                <td>0.0112%</td>
            </tr>

            <tr>
                <td>3</td>
                <td>10.32%</td>
                <td>28</td>
                <td>0.339%</td>
                <td>53</td>
                <td>0.0593%</td>
                <td>78</td>
                <td>0.0103%</td>
            </tr>

            <tr>
                <td>4</td>
                <td>6.02%</td>
                <td>29</td>
                <td>0.314%</td>
                <td>54</td>
                <td>0.0558%</td>
                <td>79</td>
                <td>0.0095%</td>
            </tr>

            <tr>
                <td>5</td>
                <td>3.87%</td>
                <td>30</td>
                <td>0.288%</td>
                <td>55</td>
                <td>0.0524%</td>
                <td>80</td>
                <td>0.0086%</td>
            </tr>

            <tr>
                <td>6</td>
                <td>2.80%</td>
                <td>31</td>
                <td>0.262%</td>
                <td>56</td>
                <td>0.0490%</td>
                <td>81</td>
                <td>0.0082%</td>
            </tr>

            <tr>
                <td>7</td>
                <td>2.26%</td>
                <td>32</td>
                <td>0.248%</td>
                <td>57</td>
                <td>0.0455%</td>
                <td>82</td>
                <td>0.0077%</td>
            </tr>

            <tr>
                <td>8</td>
                <td>1.83%</td>
                <td>33</td>
                <td>0.235%</td>
                <td>58</td>
                <td>0.0421%</td>
                <td>83</td>
                <td>0.0073%</td>
            </tr>

            <tr>
                <td>9</td>
                <td>1.51%</td>
                <td>34</td>
                <td>0.221%</td>
                <td>59</td>
                <td>0.0387%</td>
                <td>84</td>
                <td>0.0069%</td>
            </tr>

            <tr>
                <td>10</td>
                <td>1.30%</td>
                <td>35</td>
                <td>0.207%</td>
                <td>60</td>
                <td>0.0352%</td>
                <td>85</td>
                <td>0.0064%</td>
            </tr>

            <tr>
                <td>11</td>
                <td>1.19%</td>
                <td>36</td>
                <td>0.193%</td>
                <td>61</td>
                <td>0.0335%</td>
                <td>86</td>
                <td>0.0060%</td>
            </tr>

            <tr>
                <td>12</td>
                <td>1.08%</td>
                <td>37</td>
                <td>0.180%</td>
                <td>62</td>
                <td>0.0318%</td>
                <td>87</td>
                <td>0.0056%</td>
            </tr>

            <tr>
                <td>13</td>
                <td>0.98%</td>
                <td>38</td>
                <td>0.166%</td>
                <td>63</td>
                <td>0.0301%</td>
                <td>88</td>
                <td>0.0052%</td>
            </tr>

            <tr>
                <td>14</td>
                <td>0.87%</td>
                <td>39</td>
                <td>0.152%</td>
                <td>64</td>
                <td>0.0284%</td>
                <td>89</td>
                <td>0.0047%</td>
            </tr>

            <tr>
                <td>15</td>
                <td>0.76%</td>
                <td>40</td>
                <td>0.138%</td>
                <td>65</td>
                <td>0.0266%</td>
                <td>90</td>
                <td>0.0043%</td>
            </tr>

            <tr>
                <td>16</td>
                <td>0.72%</td>
                <td>41</td>
                <td>0.131%</td>
                <td>66</td>
                <td>0.0249%</td>
                <td>91</td>
                <td>0.0041%</td>
            </tr>

            <tr>
                <td>17</td>
                <td>0.67%</td>
                <td>42</td>
                <td>0.125%</td>
                <td>67</td>
                <td>0.0232%</td>
                <td>92</td>
                <td>0.0039%</td>
            </tr>

            <tr>
                <td>18</td>
                <td>0.63%</td>
                <td>43</td>
                <td>0.118%</td>
                <td>68</td>
                <td>0.0215%</td>
                <td>93</td>
                <td>0.0037%</td>
            </tr>

            <tr>
                <td>19</td>
                <td>0.59%</td>
                <td>44</td>
                <td>0.111%</td>
                <td>69</td>
                <td>0.0198%</td>
                <td>94</td>
                <td>0.0034%</td>
            </tr>

            <tr>
                <td>20</td>
                <td>0.55%</td>
                <td>45</td>
                <td>0.104%</td>
                <td>70</td>
                <td>0.0180%</td>
                <td>95</td>
                <td>0.0032%</td>
            </tr>

            <tr>
                <td>21</td>
                <td>0.52%</td>
                <td>46</td>
                <td>0.097%</td>
                <td>71</td>
                <td>0.0172%</td>
                <td>96</td>
                <td>0.0030%</td>
            </tr>

            <tr>
                <td>22</td>
                <td>0.49%</td>
                <td>47</td>
                <td>0.090%</td>
                <td>72</td>
                <td>0.0155%</td>
                <td>97</td>
                <td>0.0028%</td>
            </tr>

            <tr>
                <td>23</td>
                <td>0.47%</td>
                <td>48</td>
                <td>0.083%</td>
                <td>73</td>
                <td>0.0146%</td>
                <td>98</td>
                <td>0.0026%</td>
            </tr>

            <tr>
                <td>24</td>
                <td>0.44%</td>
                <td>49</td>
                <td>0.076%</td>
                <td>74</td>
                <td>0.0137%</td>
                <td>99</td>
                <td>0.0024%</td>
            </tr>

            <tr>
                <td>25</td>
                <td>0.42%</td>
                <td>50</td>
                <td>0.070%</td>
                <td>75</td>
                <td>0.0129%</td>
                <td>100</td>
                <td>0.0021%</td>
            </tr>

        </table>

        <p>To ensure rewards are paid for active participation, a user would need to do the following to qualify for the following OpenFPL gameplay rewards:</p>

        <ul className='mb-4'>
            <li>A user must have made at least 2 changes in a month to qualify for that month's club leaderboard rewards and monthly ATH record rewards.</li>
            <li>A user must have made at least 1 change in a gameweek to qualify for that week's leaderboard rewards, highest-scoring match player rewards and weekly ATH record rewards.</li>
            <li>Rewards for the season total, most valuable team have and annual ATH have no entry restrictions as it is based on the cumulative action of managers transfers throughout the season.</li>
        </ul>       

        <h5>Governance Rewards (25%)</h5>

        <ul>
            <li>OpenFPL values neuron holders' contributions to maintaining up-to-date Premier League data. 
                Rewards are given for raising and voting on essential proposals, such as scheduling, player transfers, and updating player information. 
                Failed proposals incur a 10 $FPL cost, contributing to the DAO’s treasury.</li>
        </ul>

        <p className='mb-4'>The OpenFPL DAO is an innovative approach to fantasy football, combining real-time data accuracy with rewarding community involvement. 
            By aligning rewards with active participation, OpenFPL ensures a vibrant, informed, and engaged user base.</p>


    </div>
  );
};

export default DAO;

// src/OpenFPL_frontend/src/lib/components/whitepaper/dao.svelte
<div class="m-4">
  <h1 class="default-header">OpenFPL DAO</h1>
  <p class="my-4">
    OpenFPL functions entirely on-chain as a DAO, aspiring to operate under
    the Internet Computer’s Service Nervous System. The DAO is structured to
    run in parallel with the Premier League season, relying on input from its
    neuron holders who are rewarded for maintaining independence from
    third-party services.
  </p>

  <h2 class="default-sub-header">DAO Reward Structure</h2>
  <p class="my-2">
    The DAO incentivizes participation through monthly minting of new FPL
    tokens, calculated annually as 2.5% of the total $FPL supply as of August
    1st. These tokens are allocated to:
  </p>

  <ul class="list-disc ml-4">
    <li>Gameplay Rewards (75%)</li>
    <li>Governance Rewards (25%)</li>
  </ul>

  <h2 class="default-sub-header mt-4">Gameplay Rewards (75%)</h2>
  <p class="my-2">
    The DAO is designed to reward users for their expertise in fantasy
    football, with rewards distributed weekly, monthly, and annually based on
    performance. The rewards are tiered to encourage ongoing engagement.
    Here’s the breakdown:
  </p>

  <ul class="list-disc ml-4">
    <li>
      Global Season Leaderboard Rewards: 30% for the top 100 global season
      positions.
    </li>
    <li>
      Club Monthly Leaderboard Rewards: 20% for the top 100 in each monthly
      club leaderboard, adjusted for the number of fans in each club.
    </li>
    <li>
      Global Weekly Leaderboard Rewards: 15% for the top 100 weekly positions.
    </li>
    <li>
      Most Valuable Team Rewards: 10% for the top 100 most valuable teams at
      season's end.
    </li>
    <li>
      Highest Scoring Match Player Rewards: 10% split among managers selecting
      the highest-scoring player in a fixture.
    </li>
    <li>
      Weekly/Monthly/Season ATH Score Rewards: 5% each, reserved for breaking
      all-time high scores in respective categories.
    </li>
  </ul>

  <p class="my-2">
    A user is rewarded for their leaderboard position across the top 100
    positions. The following is a breakdown of the reward share for each
    position:
  </p>
  <table class="w-full text-center border-collapse striped mb-8 mt-8">
    <tr>
      <th>Pos</th>
      <th>Share</th>
      <th>Pos</th>
      <th>Share</th>
      <th>Pos</th>
      <th>Share</th>
      <th>Pos</th>
      <th>Share</th>
    </tr>

    <tr>
      <td>1</td>
      <td>36.09%</td>
      <td>26</td>
      <td>0.391%</td>
      <td>51</td>
      <td>0.0662%</td>
      <td>76</td>
      <td>0.012%</td>
    </tr>

    <tr>
      <td>2</td>
      <td>18.91%</td>
      <td>27</td>
      <td>0.365%</td>
      <td>52</td>
      <td>0.0627%</td>
      <td>77</td>
      <td>0.0112%</td>
    </tr>

    <tr>
      <td>3</td>
      <td>10.32%</td>
      <td>28</td>
      <td>0.339%</td>
      <td>53</td>
      <td>0.0593%</td>
      <td>78</td>
      <td>0.0103%</td>
    </tr>

    <tr>
      <td>4</td>
      <td>6.02%</td>
      <td>29</td>
      <td>0.314%</td>
      <td>54</td>
      <td>0.0558%</td>
      <td>79</td>
      <td>0.0095%</td>
    </tr>

    <tr>
      <td>5</td>
      <td>3.87%</td>
      <td>30</td>
      <td>0.288%</td>
      <td>55</td>
      <td>0.0524%</td>
      <td>80</td>
      <td>0.0086%</td>
    </tr>

    <tr>
      <td>6</td>
      <td>2.80%</td>
      <td>31</td>
      <td>0.262%</td>
      <td>56</td>
      <td>0.0490%</td>
      <td>81</td>
      <td>0.0082%</td>
    </tr>

    <tr>
      <td>7</td>
      <td>2.26%</td>
      <td>32</td>
      <td>0.248%</td>
      <td>57</td>
      <td>0.0455%</td>
      <td>82</td>
      <td>0.0077%</td>
    </tr>

    <tr>
      <td>8</td>
      <td>1.83%</td>
      <td>33</td>
      <td>0.235%</td>
      <td>58</td>
      <td>0.0421%</td>
      <td>83</td>
      <td>0.0073%</td>
    </tr>

    <tr>
      <td>9</td>
      <td>1.51%</td>
      <td>34</td>
      <td>0.221%</td>
      <td>59</td>
      <td>0.0387%</td>
      <td>84</td>
      <td>0.0069%</td>
    </tr>

    <tr>
      <td>10</td>
      <td>1.30%</td>
      <td>35</td>
      <td>0.207%</td>
      <td>60</td>
      <td>0.0352%</td>
      <td>85</td>
      <td>0.0064%</td>
    </tr>

    <tr>
      <td>11</td>
      <td>1.19%</td>
      <td>36</td>
      <td>0.193%</td>
      <td>61</td>
      <td>0.0335%</td>
      <td>86</td>
      <td>0.0060%</td>
    </tr>

    <tr>
      <td>12</td>
      <td>1.08%</td>
      <td>37</td>
      <td>0.180%</td>
      <td>62</td>
      <td>0.0318%</td>
      <td>87</td>
      <td>0.0056%</td>
    </tr>

    <tr>
      <td>13</td>
      <td>0.98%</td>
      <td>38</td>
      <td>0.166%</td>
      <td>63</td>
      <td>0.0301%</td>
      <td>88</td>
      <td>0.0052%</td>
    </tr>

    <tr>
      <td>14</td>
      <td>0.87%</td>
      <td>39</td>
      <td>0.152%</td>
      <td>64</td>
      <td>0.0284%</td>
      <td>89</td>
      <td>0.0047%</td>
    </tr>

    <tr>
      <td>15</td>
      <td>0.76%</td>
      <td>40</td>
      <td>0.138%</td>
      <td>65</td>
      <td>0.0266%</td>
      <td>90</td>
      <td>0.0043%</td>
    </tr>

    <tr>
      <td>16</td>
      <td>0.72%</td>
      <td>41</td>
      <td>0.131%</td>
      <td>66</td>
      <td>0.0249%</td>
      <td>91</td>
      <td>0.0041%</td>
    </tr>

    <tr>
      <td>17</td>
      <td>0.67%</td>
      <td>42</td>
      <td>0.125%</td>
      <td>67</td>
      <td>0.0232%</td>
      <td>92</td>
      <td>0.0039%</td>
    </tr>

    <tr>
      <td>18</td>
      <td>0.63%</td>
      <td>43</td>
      <td>0.118%</td>
      <td>68</td>
      <td>0.0215%</td>
      <td>93</td>
      <td>0.0037%</td>
    </tr>

    <tr>
      <td>19</td>
      <td>0.59%</td>
      <td>44</td>
      <td>0.111%</td>
      <td>69</td>
      <td>0.0198%</td>
      <td>94</td>
      <td>0.0034%</td>
    </tr>

    <tr>
      <td>20</td>
      <td>0.55%</td>
      <td>45</td>
      <td>0.104%</td>
      <td>70</td>
      <td>0.0180%</td>
      <td>95</td>
      <td>0.0032%</td>
    </tr>

    <tr>
      <td>21</td>
      <td>0.52%</td>
      <td>46</td>
      <td>0.097%</td>
      <td>71</td>
      <td>0.0172%</td>
      <td>96</td>
      <td>0.0030%</td>
    </tr>

    <tr>
      <td>22</td>
      <td>0.49%</td>
      <td>47</td>
      <td>0.090%</td>
      <td>72</td>
      <td>0.0155%</td>
      <td>97</td>
      <td>0.0028%</td>
    </tr>

    <tr>
      <td>23</td>
      <td>0.47%</td>
      <td>48</td>
      <td>0.083%</td>
      <td>73</td>
      <td>0.0146%</td>
      <td>98</td>
      <td>0.0026%</td>
    </tr>

    <tr>
      <td>24</td>
      <td>0.44%</td>
      <td>49</td>
      <td>0.076%</td>
      <td>74</td>
      <td>0.0137%</td>
      <td>99</td>
      <td>0.0024%</td>
    </tr>

    <tr>
      <td>25</td>
      <td>0.42%</td>
      <td>50</td>
      <td>0.070%</td>
      <td>75</td>
      <td>0.0129%</td>
      <td>100</td>
      <td>0.0021%</td>
    </tr>
  </table>

  <p class="my-2">
    To ensure rewards are paid for active participation, a user would need to
    do the following to qualify for the following OpenFPL gameplay rewards:
  </p>

  <ul class="list-disc ml-4">
    <li>
      A user must have made at least 2 changes in a month to qualify for that
      month's club leaderboard rewards and monthly ATH record rewards.
    </li>
    <li>
      A user must have made at least 1 change in a gameweek to qualify for
      that week's leaderboard rewards, highest-scoring match player rewards
      and weekly ATH record rewards.
    </li>
    <li>
      Rewards for the season total, most valuable team have and annual ATH
      have no entry restrictions as it is based on the cumulative action of
      managers transfers throughout the season.
    </li>
  </ul>

  <h2 class="default-sub-header mt-4">Governance Rewards (25%)</h2>
  <p class="my-2">
    OpenFPL values neuron holders' contributions to maintaining up-to-date
    Premier League data. Rewards are given for raising and voting on essential
    proposals, such as scheduling, player transfers, and updating player
    information. Failed proposals incur a 10 $FPL cost, contributing to the
    DAO’s treasury.
  </p>
  <p class="my-4">
    The OpenFPL DAO is an innovative approach to fantasy football, combining
    real-time data accuracy with rewarding community involvement. By aligning
    rewards with active participation, OpenFPL ensures a vibrant, informed,
    and engaged user base.
  </p>
</div>

<style>
  .striped tr:nth-child(odd) {
    background-color: rgba(46, 50, 58, 0.6);
  }
</style>
