// src/OpenFPL_frontend/src/components/gameplay.jsx
import React, { useState, useEffect } from 'react';
import { Container, Spinner, Row, Col, Card, Table } from 'react-bootstrap';

const Gameplay = () => {
  
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      await fetchViewData();
      setIsLoading(false);
    };
    fetchData();
  }, []);

  const fetchViewData = async () => {
    
  };
  
  return (
    isLoading ? (
      <div className="customOverlay d-flex flex-column align-items-center justify-content-center">
        <Spinner animation="border" />
        <p className='text-center mt-1'>Loading</p>
      </div>) 
      :
      <Container className="flex-grow-1 my-5">
        <Row>
          <Col md={12}>
            <Card className="mb-4">
              <Card.Header><h2 className="mt-4 mb-4">OpenFPL Gameplay Rules</h2></Card.Header>
              <Card.Body>
                <Card.Text>Please see below detailed rules of the OpenFPL fantasy football game.</Card.Text>
                <p>Users will setup their team before the gameweek deadline each week. When playing OpenFPL, users have the chance to win FPL tokens depending on how well the players in their team perform.</p>

                <p>The users select 15 players, 11 playing and 4 substitutes from any Premier League team. Users have a budget of 120m to pick a team at the start of the season. 
                  No more than 3 players from a single Premier League club can be in a fantasy football team.</p>

                <p>In January, a user can change their entire team once. </p>

                <p>A players value may go up or down based on a player pricing algorithm.</p>

                <p>Player ratings are set either at the start of the DAO or by DAO proposal. These ratings are then adjusted each week by the average ratings for that player by DAO neuron holders.</p>

                <p>During a gameweek substitutes are not included in a users score. A user is allowed to make 2 transfers per week which are never carried over.</p>

                <p>A user can make a player their captain each gameweek and that player will receive double points. </p>

                <p>The following bonuses can be played once a season by a user:</p>
                <p>- 'Dynamic Duo' bonus: A bonus for effective team partnerships. If any two players from the same club within your fantasy team combine to score a goal (one assisting and the other scoring), 
                  you'll earn bonus points. </p>
                <p>- 'Double Club' bonus: All players from a chosen team in their fantasy squad will have their points doubled for that gameweek. 
                  This power play must be declared before the gameweek deadline.</p>
                <p>-'Hat-trick Bonus': When a user correctly predicts and owns the player who scores a hat-trick they will receive a bonus.</p>
                <p>-'Penalty Save Bonus': When a user correctly predicts and owns the goalkeeper who saves a penalty they will receive a bonus.</p>
                <p>-'Red Card Bonus': When a user correctly predicts and owns the player who receives a red card they will receive a bonus.</p>
                <p>- 'Prodigy Bonus': A user can choose one player under the age of 21 from their squad at the start of the season. 
                  If this chosen player scores or assists any goal, the user receives bonus points.</p>
               

                <p>The user can get the following points during a gameweek for their team:</p>

                <Table bordered className="table-fixed mt-4">
                  <colgroup>
                    <col style={{width: '70%'}} />
                    <col style={{width: '30%'}} />
                  </colgroup>
                  <thead>
                    <tr>
                      <th>For</th>
                      <th>Points</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Playing up to 60 minutes.</td>
                      <td>1</td>
                    </tr>
                    <tr>
                      <td>Playing 60 minutes or more (excluding stoppage time).</td>
                      <td>2</td>
                    </tr>
                    <tr>
                      <td>Goal scored by a goalkeeper or defender.</td>
                      <td>6</td>
                    </tr>
                    <tr>
                      <td>Goal scored by a midfielder.</td>
                      <td>5</td>
                    </tr>
                    <tr>
                      <td>Goal scored by a forward.</td>
                      <td>4</td>
                    </tr>
                    <tr>
                      <td>Assisting a goal.</td>
                      <td>3</td>
                    </tr>
                    <tr>
                      <td>Defender and goalkeeper clean sheets.</td>
                      <td>4</td>
                    </tr>
                    <tr>
                      <td>Midfielder clean sheet bonus.</td>
                      <td>1</td>
                    </tr>
                    <tr>
                      <td>3 keeper saves.</td>
                      <td>1</td>
                    </tr>
                    <tr>
                      <td>Penalty save.</td>
                      <td>5</td>
                    </tr>
                    <tr>
                      <td>Penalty miss.</td>
                      <td>-2</td>
                    </tr>
                    <tr>
                      <td>Bonus points.</td>
                      <td>1-3</td>
                    </tr>
                    <tr>
                      <td>Goalkeeper or defender concedes 2 goals.</td>
                      <td>-1</td>
                    </tr>
                    <tr>
                      <td>Yellow card received.</td>
                      <td>-1</td>
                    </tr>
                    <tr>
                      <td>Red card received.</td>
                      <td>-3</td>
                    </tr>
                    <tr>
                      <td>Own goal scored.</td>
                      <td>-2</td>
                    </tr>
                    <tr>
                      <td>Dynamic Duo Bonus (each time one player assists another for a goal and both players are from the same club  and in your team.)</td>
                      <td>4</td>
                    </tr>
                    <tr>
                      <td>Double Club Bonus (all points from a chosen club's players are doubled for a gameweek)</td>
                      <td>2x</td>
                    </tr>
                    <tr>
                      <td>Hat-trick Bonus (a player scores three goals in a match)</td>
                      <td>25</td>
                    </tr>
                    <tr>
                      <td>Penalty Save Bonus (a player saves a penalty)</td>
                      <td>50</td>
                    </tr>
                    <tr>
                      <td>Prodigy Bonus (a player under the age of 21 scores or assists a goal)</td>
                      <td>4</td>
                    </tr>
                  </tbody>
                </Table>
              </Card.Body>
            </Card>
          </Col>
        </Row>
      </Container>
    );
};

export default Gameplay;

// src/OpenFPL_frontend/src/lib/components/whitepaper/gameplay.svelte
<div class="m-4">
  <h1 class="default-header">OpenFPL Gameplay</h1>
  <p class="my-4">
    At OpenFPL, our gameplay rules are designed to create an immersive,
    engaging, and unique fantasy football experience. We understand the passion
    and strategy that goes into fantasy football, and our gameplay rules are
    crafted to reflect this, enhancing the fun and competitiveness of each
    gameweek.
  </p>

  <h2 class="default-header">Starting Funds and Team Composition</h2>
  <p class="my-2">
    Each user begins their journey with £300m, a budget to strategically build
    their dream team. The value of players fluctuates based on community ratings
    within the DAO. If a player's performance garners enough votes, their value
    can either increase or decrease by £0.25m each gameweek.
  </p>
  <p class="my-2">
    In terms of team structure, each user's team consists of 11 players. Picking
    from a range of clubs is key, so a maximum of two players from any single
    club can be selected. Teams must adhere to a valid formation: 1 goalkeeper,
    3-5 defenders, 3-5 midfielders, and 1-3 strikers.
  </p>

  <h2 class="default-header mt-4">Transfers and Team Management</h2>
  <p class="my-2">
    Flexibility is a cornerstone of our gameplay. Users can make up to three
    transfers per week, allowing for dynamic team management and adaptation to
    the ever-changing football landscape. These transfers don't roll over,
    encouraging active participation each week. There are no substitutes in our
    game, eliminating the frustration of unused bench points.
  </p>
  <p class="my-2">
    Each January, users can overhaul their team completely once, adding another
    strategic layer to the game reflecting the January transfer window.
  </p>

  <h2 class="default-header mt-4">Scoring System</h2>
  <p class="my-2">
    Our scoring system rewards players for key contributions on the field:
  </p>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Appearing in the game:
    </div>
    <div class="flex min-w-[50px] min-w-none">+5 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Every 3 saves a goalkeeper makes:
    </div>
    <div class="flex min-w-[50px]">+5 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Goalkeeper or defender cleansheet:
    </div>
    <div class="flex min-w-[50px]">+10 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Forward scores a goal:
    </div>
    <div class="flex min-w-[50px]">+10 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Midfielder or Forward assists a goal:
    </div>
    <div class="flex min-w-[50px]">+10 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Midfielder scores a goal:
    </div>
    <div class="flex min-w-[50px]">+15 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Goalkeeper or defender assists a goal:
    </div>
    <div class="flex min-w-[50px]">+15 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Goalkeeper or defender scores a goal:
    </div>
    <div class="flex min-w-[50px]">+20 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Goalkeeper saves a penalty:
    </div>
    <div class="flex min-w-[50px]">+20 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Player is highest scoring player in match:
    </div>
    <div class="flex min-w-[50px]">+25 points</div>
  </div>

  <p class="my-2">
    Points are also deducted for the following on field events:
  </p>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Player receives a red card:
    </div>
    <div class="flex min-w-[50px]">-20 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Player misses a penalty:
    </div>
    <div class="flex min-w-[50px]">-15 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      Each time a goalkeeper or defender concedes 2 goals:
    </div>
    <div class="flex min-w-[50px]">-15 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      A player scores an own goal:
    </div>
    <div class="flex min-w-[50px]">-10 points</div>
  </div>

  <div class="flex flex-row">
    <div class="flex-1 mr-4 md:flex-grow-0 md:min-w-[500px]">
      A player receives a yellow card:
    </div>
    <div class="flex min-w-[50px]">-5 points</div>
  </div>

  <h2 class="default-header mt-4">Bonuses</h2>
  <p class="my-2">
    OpenFPL elevates the gameplay with a diverse set of bonuses. These bonuses
    play a pivotal role in keeping OpenFPL's gameplay both fresh and
    exhilarating. Their strategic implementation allows for significant shifts
    in the leaderboard, ensuring that the competition remains open and dynamic.
    With these bonuses, any user, regardless of their position, has the
    potential to make a substantial leap in the rankings. This unpredictability
    means that victory is within reach for every participant, fostering a
    thrilling environment where every gameweek holds the promise of a shake-up
    at the top of the leaderboard. Our bonuses are as follows:
  </p>

  <div class="flex flex-row">
    <div class="flex mr-4 min-w-[100px] xs:min-w-[110px] sm:min-w-[150px]">
      Goal Getter:
    </div>
    <div class="flex-1">
      X3 multiplier for each goal scored by a selected player.
    </div>
  </div>

  <div class="flex flex-row">
    <div class="flex mr-4 min-w-[100px] xs:min-w-[110px] sm:min-w-[150px]">
      Pass Master:
    </div>
    <div class="flex-1">
      X3 multiplier for each assist by a selected player.
    </div>
  </div>

  <div class="flex flex-row">
    <div class="flex mr-4 min-w-[100px] xs:min-w-[110px] sm:min-w-[150px]">
      No Entry:
    </div>
    <div class="flex-1">
      X3 multiplier for a selected goalkeeper/defender for a clean sheet.
    </div>
  </div>

  <div class="flex flex-row">
    <div class="flex mr-4 min-w-[100px] xs:min-w-[110px] sm:min-w-[150px]">
      Safe Hands:
    </div>
    <div class="flex-1">X3 multiplier for a goalkeeper making 5 saves.</div>
  </div>

  <div class="flex flex-row">
    <div class="flex mr-4 min-w-[100px] xs:min-w-[110px] sm:min-w-[150px]">
      Captain Fantastic:
    </div>
    <div class="flex-1">
      X2 multiplier on the captain’s score for scoring a goal.
    </div>
  </div>

  <div class="flex flex-row">
    <div class="flex mr-4 min-w-[100px] xs:min-w-[110px] sm:min-w-[150px]">
      Team Boost:
    </div>
    <div class="flex-1">X2 multiplier for all players from a single club.</div>
  </div>

  <div class="flex flex-row">
    <div class="flex mr-4 min-w-[100px] xs:min-w-[110px] sm:min-w-[150px]">
      Brace Bonus:
    </div>
    <div class="flex-1">X2 multiplier for any player scoring 2+ goals.</div>
  </div>

  <div class="flex flex-row">
    <div class="flex mr-4 min-w-[100px] xs:min-w-[110px] sm:min-w-[150px]">
      Hat-Trick Hero:
    </div>
    <div class="flex-1">X3 multiplier for any player scoring 3+ goals.</div>
  </div>

  <div class="flex flex-row">
    <div class="flex mr-4 min-w-[100px] xs:min-w-[110px] sm:min-w-[150px]">
      Countrymen:
    </div>
    <div class="flex-1">
      Double points for players of a selected nationality.
    </div>
  </div>

  <div class="flex flex-row">
    <div class="flex mr-4 min-w-[100px] xs:min-w-[110px] sm:min-w-[150px]">
      Youth Prospects:
    </div>
    <div class="flex-1">Double points for players under 21.</div>
  </div>

  <h2 class="default-header mt-4">Star Player</h2>
  <p class="my-2">
    Each week a user can select a star player. This player will receive double
    points for the gameweek. If one is not set by the start of the gameweek it
    will automatically be set to the most valuable player in your team.
  </p>

  <p class="my-4">
    OpenFPL's gameplay combines strategic team management, a dynamic scoring
    system, and diverse bonuses, offering a unique and competitive fantasy
    football experience. Each decision impacts your journey through the Premier
    League season, where football knowledge and strategy lead to rewarding
    outcomes.
  </p>
</div>
