// src/OpenFPL_frontend/src/lib/components/confirm-fixture-data-modal.svelte
<script lang="ts">
    export let show = false;
    export let onHide: () => void;
    export let onConfirm: () => void;
  </script>
  
  {#if show}
    <div class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full">
      <div class="relative top-20 mx-auto p-5 border w-3/4 shadow-lg rounded-md bg-white">
        <div class="flex justify-between items-center">
          <h4 class="text-lg font-bold">Confirm Fixture Data</h4>
          <button class="text-black" on:click={onHide}>✕</button>
        </div>
        <div class="my-5">
          <h1>Please confirm your fixture data.</h1>
          <p class="text-sm text-gray-600">
            You will not be able to edit your submission and entries that differ from the accepted consensus data will not receive $FPL rewards. 
            If consensus has already been reached for the fixture your submission will also not be counted.
          </p>
        </div>
        <div class="flex justify-end gap-3">
          <button class="px-4 py-2 border rounded text-black" on:click={onHide}>Cancel</button>
          <button class="px-4 py-2 bg-blue-500 text-white rounded" on:click={onConfirm}>Confirm</button>
        </div>
      </div>
    </div>
  {/if}

// src/OpenFPL_frontend/src/components/governanace/fixture-validation/confirm-fixture-data-modal.jsx
import React from 'react';
import { Modal, Button} from 'react-bootstrap';

const ConfirmFixtureDataModal = ({ show, onHide, onConfirm  }) => {
    
    return (
        <Modal show={show} onHide={onHide} centered>
            <Modal.Header closeButton>Confirm Fixture Data</Modal.Header>
            <Modal.Body>
                <h1>Please confirm your fixture data.</h1>
                <p className='warning-text small-text'>You will not be able to edit your submission and entries that differ from the accepted consensus data will not receive $FPL rewards. 
                If consensus has already been reached for the fixture your submission will also not be counted.</p>
            </Modal.Body>
            <Modal.Footer>
                <Button variant="secondary" onClick={onHide}>
                    Cancel
                </Button>
                <Button variant="primary" onClick={onConfirm}>
                    Confirm
                </Button>
            </Modal.Footer>
        </Modal>
    );
   
};


export default ConfirmFixtureDataModal;
