// src/OpenFPL_frontend/src/lib/components/player-events-modal.svelte
<script lang="ts">
    import { writable, get, type Writable } from "svelte/store";
    import type { PlayerDTO, PlayerEventData } from '../../../../declarations/player_canister/player_canister.did';
    export let show = false;
    export let player: PlayerDTO;
    export let fixtureId: number;
    export let playerEventData: Writable<[] | PlayerEventData[]>;

    let eventType = -1;
    let eventStartTime = 0;
    let eventEndTime = 0;

    const eventOptions = [
        { id: 0, label: 'Appearance' },
        { id: 1, label: 'Goal Scored' },
        { id: 2, label: 'Goal Assisted' },
        { id: 7, label: 'Penalty Missed' },
        { id: 8, label: 'Yellow Card' },
        { id: 9, label: 'Red Card' },
        { id: 10, label: 'Own Goal' }
    ];
    
    function handleAddEvent() {
      if (eventType && eventStartTime !== null && eventEndTime !== null) {
        const newEvent = {
            playerId: player.id,
            eventType: Number(eventType),
            eventStartMinute: Number(eventStartTime),
            eventEndMinute: Number(eventEndTime),
            fixtureId: fixtureId,
            teamId: player.teamId
            
        };
        let updatedEvents: PlayerEventData[] = [...get(playerEventData), newEvent];
        playerEventData.set(updatedEvents);
        eventStartTime = 0;
        eventEndTime = 0;
        eventType = -1;
        }
    }
  
    function handleRemoveEvent(indexToRemove: number) {
      playerEventData.update(currentEvents => {
            return currentEvents.filter((_, index) => index !== indexToRemove);
        });
    }

  </script>
  
  {#if show}
    <div class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full">
      <div class="relative top-20 mx-auto p-5 border w-3/4 shadow-lg rounded-md bg-white">
        {#if player}
          <div class="flex justify-between items-center">
            <h4 class="text-lg font-bold">{player.firstName !== "" ? player.firstName.charAt(0) + "." : ""} {player.lastName} - Match Events</h4>
            <button class="text-black" on:click={() => show = false}>✕</button>
          </div>

          <div class="mt-4 p-4 border-t border-gray-200">
            <h4 class="text-lg font-bold mb-3">Add Event</h4>
            <div class="flex flex-col gap-3">
              <div>
                  <label for="eventType" class="block text-sm font-medium text-gray-700">Event Type</label>
                  <select id="eventType" bind:value={eventType} class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md">
                      <option value="-1" disabled>Select event type</option>
                      {#each eventOptions as option}
                          <option value={option.id}>{option.label}</option>
                      {/each}
                  </select>
              </div>
              <div>
                  <label for="startMinute" class="block text-sm font-medium text-gray-700">Start Minute</label>
                  <input type="number" id="startMinute" bind:value={eventStartTime} class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md" placeholder="Enter start minute">
              </div>
              <div>
                  <label for="endMinute" class="block text-sm font-medium text-gray-700">End Minute</label>
                  <input type="number" id="endMinute" bind:value={eventEndTime} class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md" placeholder="Enter end minute">
              </div>
              <button class="mt-2 px-4 py-2 bg-blue-500 text-white rounded" on:click={handleAddEvent}>Add Event</button>
            </div>
          </div>


          <div class="mt-4">
            <ul class="list-disc pl-5">
              {#each $playerEventData as event, index}
                <li class="flex justify-between items-center mb-2">
                  <span>{event.eventType} - From {event.eventStartMinute} to {event.eventEndMinute} minutes</span>
                  <button class="px-3 py-1 bg-red-500 text-white rounded" on:click={() => handleRemoveEvent(index)}>
                    Remove
                  </button>
                </li>
              {/each}
            </ul>
          </div>
        {/if}
        <div class="flex justify-end gap-3 mt-4">
          <button class="px-4 py-2 bg-blue-500 text-white rounded" on:click={() => show = false}>Done</button>
        </div>
      </div>
    </div>
  {/if}

// src/OpenFPL_frontend/src/components/governanace/fixture-validation/player-events-modal.jsx
import React, { useState, useEffect } from 'react';
import { Modal, Form, Button, Row, Col, Table } from 'react-bootstrap';

const PlayerEventModal = ({ show, onHide, onPlayerEventAdded, player, playerEventMap  }) => {
    const [playerEvents, setPlayerEvents] = useState([]);
    const [eventType, setEventType] = useState("-1");
    const [eventStartTime, setEventStartTime] = useState("0");
    const [eventEndTime, setEventEndTime] = useState("0");

    useEffect(() => {
        if(!player){
            return;
        }
        const existingEvents = playerEventMap[player.id] || [];
        setPlayerEvents(existingEvents);
        
        setEventType("-1");
        setEventStartTime("0");
        setEventEndTime("0");
    }, [player, playerEventMap]);
    

    const getEventOptions = (position) => {
        const generalOptions = [
            { id: 0, label: 'Appearance' },
            { id: 1, label: 'Goal Scored' },
            { id: 2, label: 'Goal Assisted' },
            { id: 7, label: 'Penalty Missed' },
            { id: 8, label: 'Yellow Card' },
            { id: 9, label: 'Red Card' },
            { id: 10, label: 'Own Goal' }
        ];

        if (position === 0) {
            return [
                ...generalOptions,
                { id: 4, label: 'Keeper Save' },
                { id: 6, label: 'Penalty Saved' }
            ];
        }

        return generalOptions;
    };

    const getEventTypeLabel = (id) => {
        const allOptions = [
            { id: 0, label: 'Appearance' },
            { id: 1, label: 'Goal Scored' },
            { id: 2, label: 'Goal Assisted' },
            { id: 7, label: 'Penalty Missed' },
            { id: 8, label: 'Yellow Card' },
            { id: 9, label: 'Red Card' },
            { id: 10, label: 'Own Goal' },
            { id: 4, label: 'Keeper Save' },
            { id: 6, label: 'Penalty Saved' }
        ];
        const option = allOptions.find(option => option.id === id);
        return option ? option.label : '';
      };

    const handleAddEvent = () => {
        
        if (eventType && eventStartTime !== null && eventEndTime !== null) {
            const newEvent = {
                playerId: player.id,
                eventType: Number(eventType),
                eventStartTime: Number(eventStartTime),
                eventEndTime: Number(eventEndTime)
            };
            let updatedEvents = [];
            if (Array.isArray(playerEvents)) {
                updatedEvents = [...playerEvents, newEvent];
            } else {
                updatedEvents = [newEvent];
            }
            setPlayerEvents(updatedEvents);
            onPlayerEventAdded(player.id, updatedEvents);
        }
        setEventStartTime(""); 
        setEventEndTime("");
    };
    
    

    const handleRemoveEvent = (indexToRemove) => {
        const updatedEvents = playerEvents.filter((_, index) => index !== indexToRemove);
        setPlayerEvents(updatedEvents);
        onPlayerEventAdded(player.id, updatedEvents);
    };


    return (
        <Modal show={show} onHide={onHide} centered>
        <Modal.Header closeButton>
            {player && <Modal.Title>{player.firstName != "" ? player.firstName.charAt(0) + "." : ""} {player.lastName} - Match Events</Modal.Title>}
        </Modal.Header>
        <Modal.Body>
            <Form>
                <Form.Group as={Row} className='mb-2'>
                    <Col xs={12}>
                        <Form.Control 
                            as="select"
                            value={eventType}
                            onChange={(e) => {setEventType(e.target.value); setEventStartTime(""); setEventEndTime("");}}>
                                <option value="">Select Event</option>
                                {player && getEventOptions(player.position).map(option => (
                                    <option key={option.id} value={option.id}>
                                        {option.label}
                                    </option>
                                ))}
                        </Form.Control>
                    </Col>
                </Form.Group>
                
                {eventType !== "0" ? (
                <Form.Group as={Row} className='mb-2'>
                            <Col xs={6}>
                            <Form.Control 
                                type="number" 
                                placeholder="Event End Time" 
                                min={0}
                                max={90}
                                value={Number(eventEndTime)}
                                onChange={(e) => {
                                    setEventStartTime(e.target.value);
                                    setEventEndTime(e.target.value);
                                }}
                                />
                            </Col>
                </Form.Group>
                    ) : (
                        <Form.Group as={Row} className='mb-2'>
                            <Col xs={6}>
                            <Form.Control 
                                type="number" 
                                placeholder="Event Start Time" 
                                min={0}
                                max={90}
                                value={Number(eventStartTime)}
                                onChange={(e) => setEventStartTime(e.target.value)}
                                />
                            </Col>
                            <Col xs={6}>
                            <Form.Control 
                                type="number" 
                                placeholder="Event End Time" 
                                min={0}
                                max={90}
                                value={Number(eventEndTime)}   // convert string to number
                                onChange={(e) => setEventEndTime(e.target.value)}
                                />
                            </Col>
                        </Form.Group>
                    )}
                <Form.Group as={Row} className='mb-2'>
                    <Col>
                        <Button className="w-100" onClick={handleAddEvent}>Add Event</Button>
                    </Col>
                </Form.Group>

                <Table responsive bordered className="table-fixed light-table">
                    <thead>
                        <tr>
                            <th>Event Type</th>
                            <th>Start Minute</th>
                            <th>End Minute</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {playerEvents.map((event, index) => (
                            <tr key={index}>
                                <td>{getEventTypeLabel(event.eventType)}</td>
                                <td>{event.eventStartTime}</td>
                                <td>{event.eventEndTime}</td>
                                <td>
                                    <Button onClick={() => handleRemoveEvent(index)}>Remove</Button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </Table>
            </Form>
        </Modal.Body>
        <Modal.Footer>
            <Button variant="primary" onClick={onHide}>
                Done
            </Button>
        </Modal.Footer>
    </Modal>
    );
   
};


export default PlayerEventModal;
