// src/OpenFPL_frontend/src/routes/add-fixture-data/+page.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { page } from "$app/stores";
  import { goto } from "$app/navigation";
  import { writable } from "svelte/store";
  import { teamStore } from "$lib/stores/team-store";
  import { fixtureStore } from "$lib/stores/fixture-store";
  import { governanceStore } from "$lib/stores/governance-store";
  import { toastsError, toastsShow } from "$lib/stores/toasts-store";
  import { loadingText } from "$lib/stores/global-stores";
  import type {
    PlayerDTO,
    PlayerEventData,
  } from "../../../../declarations/player_canister/player_canister.did";
  import type {
    Fixture,
    Team,
  } from "../../../../declarations/OpenFPL_backend/OpenFPL_backend.did";
  import { replacer } from "$lib/utils/Helpers";
  import Layout from "../Layout.svelte";
  import PlayerEventsModal from "$lib/components/fixture-validation/player-events-modal.svelte";
  import SelectPlayersModal from "$lib/components/fixture-validation/select-players-modal.svelte";
  import ConfirmFixtureDataModal from "$lib/components/fixture-validation/confirm-fixture-data-modal.svelte";
  import ClearDraftModal from "$lib/components/fixture-validation/clear-draft-modal.svelte";
  import { playerStore } from "$lib/stores/player-store";
  import LoadingIcon from "$lib/icons/LoadingIcon.svelte";

  $: fixtureId = Number($page.url.searchParams.get("id"));

  let teams: Team[] = [];
  let players: PlayerDTO[] = [];
  let fixture: Fixture | null;
  let homeTeam: Team | null;
  let awayTeam: Team | null;

  let showPlayerSelectionModal = false;
  let showPlayerEventModal = false;
  let showClearDraftModal = false;
  let showConfirmDataModal = false;

  let teamPlayers = writable<PlayerDTO[] | []>([]);
  let selectedPlayers = writable<PlayerDTO[] | []>([]);

  let selectedTeam: Team | null = null;
  let selectedPlayer: PlayerDTO | null = null;
  let playerEventData = writable<PlayerEventData[] | []>([]);
  let activeTab: string = "home";

  let isSubmitDisabled: boolean = true;
  $: isSubmitDisabled =
    $playerEventData.length == 0 ||
    $playerEventData.filter((x) => x.eventType == 0).length !=
      $selectedPlayers.length;

  let isLoading = true;

  onMount(async () => {
    try {
      await teamStore.sync();
      await fixtureStore.sync();
      await playerStore.sync();

      teamStore.subscribe((value) => {
        teams = value;
      });

      playerStore.subscribe((value) => {
        players = value;
      });

      fixtureStore.subscribe((value) => {
        fixture = value.find((x) => x.id == fixtureId)!;
        homeTeam = teams.find((x) => x.id == fixture?.homeTeamId)!;
        awayTeam = teams.find((x) => x.id == fixture?.awayTeamId)!;
        selectedTeam = homeTeam;
        teamPlayers.set(players.filter((x) => x.teamId == selectedTeam?.id));
      });

      const draftKey = `fixtureDraft_${fixtureId}`;
      const savedDraft = localStorage.getItem(draftKey);
      if (savedDraft) {
        const draftData = JSON.parse(savedDraft);
        let draftEventData = draftData.playerEventData;
        if (draftEventData) {
          playerEventData.set(draftEventData);
          updateSelectedPlayers();
        }
      }
    } catch (error) {
      toastsError({
        msg: { text: "Error fetching fixture information." },
        err: error,
      });
      console.error("Error fetching fixture information.", error);
    } finally {
      isLoading = false;
    }
  });

  onDestroy(() => {});

  async function confirmFixtureData() {
    isLoading = true;
    $loadingText = "Saving Fixture Data";
    try {
      await governanceStore.submitFixtureData(fixtureId, $playerEventData);
      localStorage.removeItem(`fixtureDraft_${fixtureId}`);
      toastsShow({
        text: "Fixture data saved.",
        level: "success",
        duration: 2000,
      });
      goto("/fixture-validation");
    } catch (error) {
      toastsError({
        msg: { text: "Error saving fixture data." },
        err: error,
      });
      console.error("Error saving fixture data: ", error);
    } finally {
      isLoading = false;
      $loadingText = "Loading";
    }
  }

  function updateSelectedPlayers() {
    const uniquePlayerIds = new Set(
      $playerEventData.map((event) => event.playerId)
    );
    const selectedPlayerObjects = players.filter((player) =>
      uniquePlayerIds.has(player.id)
    );
    selectedPlayers.set(selectedPlayerObjects);
  }

  function saveDraft() {
    const draftData = {
      playerEventData: $playerEventData,
    };
    const draftKey = `fixtureDraft_${fixtureId}`;
    localStorage.setItem(draftKey, JSON.stringify(draftData, replacer));
    toastsShow({
      text: "Draft saved.",
      level: "success",
      duration: 2000,
    });
  }

  function clearDraft() {
    playerEventData = writable<PlayerEventData[] | []>([]);
    localStorage.removeItem(`fixtureDraft_${fixtureId}`);
    toastsShow({
      text: "Draft cleared.",
      level: "success",
      duration: 2000,
    });
    closeConfirmClearDraftModal();
  }

  async function setActiveTab(tab: string) {
    await playerStore.sync();
    selectedTeam = tab === "home" ? homeTeam : awayTeam;
    teamPlayers.set(players.filter((x) => x.teamId == selectedTeam?.id));
    activeTab = tab;
  }

  function handleEditPlayerEvents(player: PlayerDTO) {
    selectedPlayer = player;
    showPlayerEventModal = true;
  }

  function closeEventPlayerEventsModal(): void {
    showPlayerEventModal = false;
    selectedPlayer = null;
  }

  function showSelectPlayersModal(): void {
    showPlayerSelectionModal = true;
  }

  function closeSelectPlayersModal(): void {
    showPlayerSelectionModal = false;
  }

  function showConfirmClearDraftModal(): void {
    showClearDraftModal = true;
  }

  function closeConfirmClearDraftModal(): void {
    showClearDraftModal = false;
  }
</script>

<Layout>
  {#if isLoading}
    <LoadingIcon />
  {:else}
    <div class="container-fluid mx-4 md:mx-16 mt-4 bg-panel">
      <div class="flex flex-col text-xs md:text-base mt-4">
        <div class="flex flex-row space-x-2 p-4">
          <button class="fpl-button px-4 py-2" on:click={showSelectPlayersModal}
            >Select Players</button
          >
          <button class="fpl-button px-4 py-2" on:click={saveDraft}
            >Save Draft</button
          >
          <button
            class="fpl-button px-4 py-2"
            on:click={showConfirmClearDraftModal}>Clear Draft</button
          >
        </div>
        <div class="flex w-full">
          <ul class="flex bg-light-gray px-4 pt-2 w-full mt-4">
            <li
              class={`mr-4 text-xs md:text-base ${
                activeTab === "home" ? "active-tab" : ""
              }`}
            >
              <button
                class={`p-2 ${
                  activeTab === "home" ? "text-white" : "text-gray-400"
                }`}
                on:click={() => setActiveTab("home")}
                >{homeTeam?.friendlyName}</button
              >
            </li>
            <li
              class={`mr-4 text-xs md:text-base ${
                activeTab === "away" ? "active-tab" : ""
              }`}
            >
              <button
                class={`p-2 ${
                  activeTab === "away" ? "text-white" : "text-gray-400"
                }`}
                on:click={() => setActiveTab("away")}
                >{awayTeam?.friendlyName}</button
              >
            </li>
          </ul>
        </div>
        <div class="flex w-full flex-col">
          <div
            class="flex items-center p-2 justify-between py-4 border-b border-gray-700 cursor-pointer w-full"
          >
            <div class="w-1/6 px-4">Player</div>
            <div class="w-1/6 px-4">Position</div>
            <div class="w-1/6 px-4">Events</div>
            <div class="w-1/6 px-4">Start</div>
            <div class="w-1/6 px-4">End</div>
            <div class="w-1/6 px-4">&nbsp;</div>
          </div>
          {#if activeTab === "home"}
            {#each $selectedPlayers.filter((x) => x.teamId === fixture?.homeTeamId) as player (player.id)}
              <div
                class="flex items-center p-2 justify-between py-4 border-b border-gray-700 cursor-pointer w-full"
              >
                <div class="w-1/6 px-4">
                  {`${
                    player.firstName.length > 0
                      ? player.firstName.charAt(0) + "."
                      : ""
                  } ${player.lastName}`}
                </div>
                {#if player.position == 0}<div class="w-1/6 px-4">GK</div>{/if}
                {#if player.position == 1}<div class="w-1/6 px-4">DF</div>{/if}
                {#if player.position == 2}<div class="w-1/6 px-4">MF</div>{/if}
                {#if player.position == 3}<div class="w-1/6 px-4">FW</div>{/if}
                <div class="w-1/6 px-4">
                  Events:
                  {$playerEventData?.length > 0 &&
                  $playerEventData?.filter((e) => e.playerId === player.id)
                    .length
                    ? $playerEventData?.filter((e) => e.playerId === player.id)
                        .length
                    : 0}
                </div>
                <div class="w-1/6 px-4">
                  {$playerEventData &&
                  $playerEventData?.length > 0 &&
                  $playerEventData?.find(
                    (e) => e.playerId === player.id && e.eventType == 0
                  )
                    ? $playerEventData?.find(
                        (e) => e.playerId === player.id && e.eventType == 0
                      )?.eventStartMinute
                    : "-"}
                </div>
                <div class="w-1/6 px-4">
                  {$playerEventData &&
                  $playerEventData?.length > 0 &&
                  $playerEventData?.find(
                    (e) => e.playerId === player.id && e.eventType == 0
                  )
                    ? $playerEventData?.find(
                        (e) => e.playerId === player.id && e.eventType == 0
                      )?.eventEndMinute
                    : "-"}
                </div>
                <div class="w-1/6 px-4">
                  <button
                    on:click={() => handleEditPlayerEvents(player)}
                    class="text-base sm:text-xs md:text-base rounded fpl-button px-3 sm:px-2 px-3 py-1 ml-1"
                  >
                    Update Events
                  </button>
                </div>
              </div>
            {/each}
          {/if}
          {#if activeTab === "away"}
            {#each $selectedPlayers.filter((x) => x.teamId === fixture?.awayTeamId) as player (player.id)}
              <div
                class="flex items-center p-2 justify-between py-4 border-b border-gray-700 cursor-pointer w-full"
              >
                <div class="w-1/6 px-4">
                  {`${
                    player.firstName.length > 0
                      ? player.firstName.charAt(0) + "."
                      : ""
                  } ${player.lastName}`}
                </div>
                {#if player.position == 0}<div class="w-1/6 px-4">GK</div>{/if}
                {#if player.position == 1}<div class="w-1/6 px-4">DF</div>{/if}
                {#if player.position == 2}<div class="w-1/6 px-4">MF</div>{/if}
                {#if player.position == 3}<div class="w-1/6 px-4">FW</div>{/if}
                <div class="w-1/6 px-4">
                  Events:
                  {$playerEventData?.length > 0 &&
                  $playerEventData?.filter((e) => e.playerId === player.id)
                    .length
                    ? $playerEventData?.filter((e) => e.playerId === player.id)
                        .length
                    : 0}
                </div>
                <div class="w-1/6 px-4">
                  {$playerEventData &&
                  $playerEventData?.length > 0 &&
                  $playerEventData?.find(
                    (e) => e.playerId === player.id && e.eventType == 0
                  )
                    ? $playerEventData?.find((e) => e.playerId === player.id)
                        ?.eventStartMinute
                    : "-"}
                </div>
                <div class="w-1/6 px-4">
                  {$playerEventData &&
                  $playerEventData?.length > 0 &&
                  $playerEventData?.find(
                    (e) => e.playerId === player.id && e.eventType == 0
                  )
                    ? $playerEventData?.find((e) => e.playerId === player.id)
                        ?.eventEndMinute
                    : "-"}
                </div>
                <div class="w-1/6 px-4">
                  <button
                    on:click={() => handleEditPlayerEvents(player)}
                    class="text-base sm:text-xs md:text-base rounded fpl-button px-3 sm:px-2 px-3 py-1 ml-1"
                  >
                    Update Events
                  </button>
                </div>
              </div>
            {/each}
          {/if}
        </div>
        <div class="flex w-full m-4">
          <h1>Summary</h1>
        </div>
        <div class="flex flex-row w-full m-4">
          <div class="text-sm font-medium flex-grow">
            Appearances: {$playerEventData.filter((x) => x.eventType == 0)
              .length}
          </div>
          <div class="text-sm font-medium flex-grow">
            Goals: {$playerEventData.filter((x) => x.eventType == 1).length}
          </div>
          <div class="text-sm font-medium flex-grow">
            Own Goals: {$playerEventData.filter((x) => x.eventType == 10)
              .length}
          </div>
          <div class="text-sm font-medium flex-grow">
            Assists: {$playerEventData.filter((x) => x.eventType == 2).length}
          </div>
          <div class="text-sm font-medium flex-grow">
            Keeper Saves: {$playerEventData.filter((x) => x.eventType == 4)
              .length}
          </div>
          <div class="text-sm font-medium flex-grow">
            Yellow Cards: {$playerEventData.filter((x) => x.eventType == 8)
              .length}
          </div>
          <div class="text-sm font-medium flex-grow">
            Red Cards: {$playerEventData.filter((x) => x.eventType == 9).length}
          </div>
          <div class="text-sm font-medium flex-grow">
            Penalties Saved: {$playerEventData.filter((x) => x.eventType == 6)
              .length}
          </div>
          <div class="text-sm font-medium flex-grow">
            Penalties Missed: {$playerEventData.filter((x) => x.eventType == 7)
              .length}
          </div>
        </div>

        <div class="items-center mt-3 flex space-x-4">
          <button
            class={`${isSubmitDisabled ? "bg-gray-500" : "fpl-purple-btn"} 
            px-4 py-2 text-white text-base font-medium rounded-md w-full shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-300`}
            on:click={confirmFixtureData}
            disabled={isSubmitDisabled}>Submit Event Data</button
          >
        </div>
      </div>
    </div>
  {/if}
</Layout>

{#if selectedTeam}
  <SelectPlayersModal
    visible={showPlayerSelectionModal}
    {teamPlayers}
    {selectedTeam}
    {selectedPlayers}
    closeModal={closeSelectPlayersModal}
  />
{/if}

{#if selectedPlayer}
  <PlayerEventsModal
    visible={showPlayerEventModal}
    player={selectedPlayer}
    {fixtureId}
    {playerEventData}
    closeModal={closeEventPlayerEventsModal}
  />
{/if}

<ConfirmFixtureDataModal
  visible={showConfirmDataModal}
  onConfirm={confirmFixtureData}
/>

<ClearDraftModal
  closeModal={closeConfirmClearDraftModal}
  visible={showClearDraftModal}
  onConfirm={clearDraft}
/>

// src/OpenFPL_frontend/src/components/governanace/pre-sns-fixture-validation/add-fixture-data.jsx
import React, { useState, useEffect, useContext } from 'react';
import { Card, Row, Col, Spinner, Button, Container, Tabs, Tab } from 'react-bootstrap';
import { DataContext } from "../../../contexts/DataContext";
import { OpenFPL_backend as open_fpl_backend } from '../../../../../declarations/OpenFPL_backend';
import { useLocation, useNavigate } from 'react-router-dom';
import PlayerEventsModal from './player-events-modal';
import PlayerSelectionModal from './select-players-modal';
import ConfirmFixtureDataModal from './confirm-fixture-data-modal';
import ConfirmClearDraftModal from './confirm-clear-draft-modal';

const PreSNSAddFixtureData = () => {
  const location = useLocation();
  const queryParams = new URLSearchParams(location.search);
  const fixtureId = queryParams.get('fixtureId');
  
  const { teams, systemState, players } = useContext(DataContext);
  const [isLoading, setIsLoading] = useState(true);
  const [fixture, setFixture] = useState(null);
  const [showPlayerSelectionModal, setShowPlayerSelectionModal] = useState(false);
  const [showPlayerEventModal, setShowPlayerEventModal] = useState(false);
  const [showConfirmDataModal, setShowConfirmDataModal] = useState(false);
  const [showConfirmClearDraftModal, setShowConfirmClearDraftModal] = useState(false);
  
  const [editingPlayerEvent, setEditingPlayerEvent] = useState(null);
  const [key, setKey] = useState('homeTeam');
  const [teamPlayers, setTeamPlayers] = useState(players.filter(x => x.teamId > 0));
  const [selectedPlayers, setSelectedPlayers] = useState({
    homeTeam: [],
    awayTeam: [],
  });
  const [playerEventMap, setPlayerEventMap] = useState({});
  const navigate = useNavigate();
  const [showDraftCleared, setShowDraftCleared] = useState(false);
  const [showDraftSaved, setShowDraftSaved] = useState(false);

 
  const handlePlayerSelection = (team, playerIds) => {
    const currentPlayerIds = selectedPlayers[team];
    const removedPlayerIds = currentPlayerIds.filter(id => !playerIds.includes(id));
    let remainingPlayerEventMap = { ...playerEventMap }; // Create a shallow copy of the playerEventMap

    if (removedPlayerIds.length > 0) {
      removedPlayerIds.forEach(removedPlayerId => {
        const {[removedPlayerId]: value, ...newRemainingPlayerEventMap} = remainingPlayerEventMap;
        remainingPlayerEventMap = newRemainingPlayerEventMap;
      });
    }
  
    setPlayerEventMap(remainingPlayerEventMap);
  
    setSelectedPlayers(prevState => ({
      ...prevState,
      [team]: playerIds,
    }));
  
    const newFixtureStats = calculateFixtureStats(remainingPlayerEventMap, players, fixture);
    setFixture(prevFixture => ({
      ...prevFixture,
      ...newFixtureStats
    }));
  
    setShowPlayerSelectionModal(false);
  };

  const handleClearDraft = () => {
      handleClearAllEvents();
      const draftKey = `fixtureDraft_${fixtureId}`;
      localStorage.removeItem(draftKey);
      setShowDraftCleared(true);
      setShowDraftSaved(false);
      setShowConfirmClearDraftModal(false);
  };

  const handleClearAllEvents = () => {
    setPlayerEventMap({});
    setSelectedPlayers({
      homeTeam: [],
      awayTeam: [],
    });
  };
  
  useEffect(() => {
    checkAndClearCacheIfNewGameweek();
    const draftKey = `fixtureDraft_${fixtureId}`;
    const draft = localStorage.getItem(draftKey);
    if (draft) {
      const reviver = (key, value) => {
          if (typeof value === 'string' && /^[0-9]+n$/.test(value)) {
              return BigInt(value.slice(0, -1));
          }
          return value;
      };
      const { selectedPlayers, playerEventMap, fixture } = JSON.parse(draft, reviver);
      setSelectedPlayers(selectedPlayers);
      setPlayerEventMap(playerEventMap);
      setFixture(fixture);
    }
  }, []);

  
  useEffect(() => {
    const fetchData = async () => {
      try {
        const fetchedFixture = await open_fpl_backend.getFixture(0,0,Number(fixtureId));
        setFixture(fetchedFixture);
      } catch (error) {
        console.error(error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchData();
  }, [fixtureId]);

  const handleSaveAsDraft = () => {
      const replacer = (key, value) => {
          if (typeof value === 'bigint') {
              return value.toString() + "n"; // Convert BigInt to string and append "n" to distinguish
          }
          return value;
      };

      
    const draftKey = `fixtureDraft_${fixtureId}`;
    localStorage.setItem(draftKey, JSON.stringify({
        selectedPlayers,
        playerEventMap,
        fixture,
    }, replacer));
    setShowDraftCleared(false);
    setShowDraftSaved(true);
  };

  const checkAndClearCacheIfNewGameweek = async () => {

      const currentGameweek = systemState.activeGameweek;
      const lastKnownGameweek = localStorage.getItem('lastKnownGameweek');
    
      if (!lastKnownGameweek || Number(lastKnownGameweek) !== currentGameweek) {
          clearFixtureCache();
          localStorage.setItem('lastKnownGameweek', String(currentGameweek));
      }
  };

  const clearFixtureCache = () => {
      for (const key in localStorage) {
          if (key.startsWith("fixtureDraft_")) {
              localStorage.removeItem(key);
          }
      }
  };

  
  const renderPlayerCard = (playerId) => {
    const player = players.find(p => p.id == playerId);
    
    const totalEvents = playerEventMap[playerId]?.length || 0;

    return (
      <Col xs={12} md={3} key={playerId} >
        <Card className="player-card mb-4">
          <Card.Header>
            <h5>{player.lastName}</h5>
            <p className='small-text mb-0 mt-0'>{player.firstName}</p>
          </Card.Header>
          <Card.Body>
            <p>Events: {totalEvents}</p>
            <Button onClick={() => handleEditPlayerEvents(player)}>Update</Button>
          </Card.Body>
        </Card>
      </Col>
    );
  };

  const handleEditPlayerEvents = (player) => {
    const playerEvents = playerEventMap[player.id];
    setEditingPlayerEvent({
      ...player,
      events: playerEvents,
    });
    setShowPlayerEventModal(true);
  };
  

  const handlePlayerEventAdded = (playerId, newEvents) => {
    const newPlayerEventMap = {
      ...playerEventMap,
      [playerId]: newEvents
    };

     setPlayerEventMap(newPlayerEventMap);
  
     const newFixtureStats = calculateFixtureStats(newPlayerEventMap, players, fixture);
    setFixture(prevFixture => ({
      ...prevFixture,
      ...newFixtureStats
    }));
  };


  if (isLoading) {
    return (
      <div className="customOverlay d-flex flex-column align-items-center justify-content-center">
        <Spinner animation="border" />
        <p className='text-center mt-1'>Loading Fixture Data...</p>
      </div>
    );
  };

  const handleSaveFixtureData = async () => {
    setShowConfirmDataModal(false);
    try {
      const playerEventsArray = [];
      for (const [playerId, playerEvents] of Object.entries(playerEventMap)) {
        const playerTeamId = players.find(p => p.id == playerId)?.teamId;
        playerEvents.forEach(event => {
          playerEventsArray.push({
            fixtureId: fixture.id,
            playerId: Number(playerId),
            eventType: Number(event.eventType),
            eventStartMinute: Number(event.eventStartTime),
            eventEndMinute: Number(event.eventEndTime),
            teamId: playerTeamId
          });
        });
      }
      setIsLoading(true);
      await open_fpl_backend.savePlayerEvents(fixture.id, playerEventsArray);
      handleClearDraft();

      //redirect to consensus page
      navigate('/governance')

    } catch (error) {
      console.error('Failed to save player events', error);
    }
  };
  

  const getTeamNameFromId = (teamId) => {
    const team = teams.find(team => team.id === teamId);
    if(!team){
      return;
    }
    return team.friendlyName;
  };

  const addTeamPlayers = (teamId, teamType) => {
    const filteredPlayers = players.filter(player => teamId === "" || player.teamId === Number(teamId));
    setTeamPlayers(filteredPlayers);
    setShowPlayerSelectionModal(true);
  };
  
  const calculateFixtureStats = (playerEventMap, players, fixture) => {
    const initialStats = {
      homeGoals: 0,
      awayGoals: 0,
      goals: 0,
      assists: 0,
      redCards: 0,
      yellowCards: 0,
      appearances: 0,
      penaltyMissed: 0,
      penaltySaves: 0,
      keeperSaves: 0,
      ownGoals: 0
    };
  
    Object.values(playerEventMap).flat().forEach((event) => {
      const playerTeam = players.find(player => player.id === event.playerId).teamId;
      const isHomeTeam = playerTeam === fixture.homeTeamId;
  
      switch(event.eventType) {
        case 0: // Appearance
          initialStats.appearances++
          break;
        case 1: // Goal Scored
          isHomeTeam ? initialStats.homeGoals++ : initialStats.awayGoals++;
          initialStats.goals++
          break;
        case 2: // Goal Assisted
          initialStats.assists++
          break;
        case 4: 
          initialStats.keeperSaves++
          break;
        case 6: 
          initialStats.penaltySaves++
          break;
        case 7: // Penalty Miss
          initialStats.penaltyMissed++
          break;
        case 8: // Yellow Card
          initialStats.yellowCards++
          break;
        case 9: // Red Card
          initialStats.redCards++
          break;
        case 10: // Own Goal
          isHomeTeam ? initialStats.awayGoals++ : initialStats.homeGoals++;
          initialStats.ownGoals++;
          break;
        // Add cases for other event types here
        default:
          break;
      }
    });
  
    return initialStats;
  };

  return (
    
    <Container className="flex-grow-1 my-5">
      <h1>Manage Fixture Data</h1>
      <br />
      
      <Card className="custom-card mt-1">
        <Card.Header>
          <Row className="fixture-header mt-4 mb-4 text-center">
            <Col className='align-self-center' xs={2}><p className='w-100 m-0 p-0 text-center'>{fixture.homeGoals}</p></Col>
            <Col className='align-self-center' xs={3}><p className='w-100 m-0 p-0 text-center small-text'>{getTeamNameFromId(fixture.homeTeamId)}</p></Col>
            <Col className='align-self-center v-symbol' xs={2}>v</Col>
            <Col className='align-self-center' xs={3}><p className='w-100 m-0 p-0 text-center small-text'>{getTeamNameFromId(fixture.awayTeamId)}</p></Col>
            <Col className='align-self-center' xs={2}><p className='w-100 m-0 p-0 text-center'>{fixture.awayGoals}</p></Col>
          </Row>
        </Card.Header>
        <Card.Body>
          <Tabs defaultActiveKey="homeTeam" id="profile-tabs" className="mt-4" activeKey={key} onSelect={(k) => setKey(k)}>
            <Tab eventKey="homeTeam" title={getTeamNameFromId(fixture.homeTeamId)}>
              <Container className="flex-grow-1 my-3">
                  <Row className="align-items-center mb-4">
                    <Col>
                      <h5>All Players</h5>
                    </Col>
                    <Col className="d-flex justify-content-end">
                    <Button onClick={() => addTeamPlayers(fixture.homeTeamId, 'homeTeam')} variant="primary">Select Players</Button>

                    </Col>
                  </Row>
                  <Row>
                    {selectedPlayers.homeTeam.map(playerId => renderPlayerCard(playerId))}
                  </Row>
              </Container>
            </Tab>
            <Tab eventKey="awayTeam" title={getTeamNameFromId(fixture.awayTeamId)}>
              <Container className="flex-grow-1 my-3">
                <Row className="align-items-center mb-4">
                  <Col>
                    <h5>All Players</h5>
                  </Col>
                  <Col className="d-flex justify-content-end">
                  <Button onClick={() => addTeamPlayers(fixture.awayTeamId, 'awayTeam')} variant="primary">Select Players</Button>

                  </Col>
                </Row>
                <Row>
                  {selectedPlayers.awayTeam.map(playerId => renderPlayerCard(playerId))}
                </Row>
              </Container>
            </Tab>
          </Tabs>

          <div className="add-fixture-data">
            <Row>
              <Col xs={12} md={4}>
                <Button className="mt-3 mb-3" variant='danger' onClick={() => setShowConfirmClearDraftModal(true)}>
                    Clear Draft
                </Button>
                {showDraftCleared && <p className='cleared-text'>Cleared.</p>}
              </Col>
              <Col xs={12} md={4}>
                <Button className="mt-3 mb-3 mr-2" variant='success' onClick={handleSaveAsDraft}>
                    Save as Draft
                </Button>
                {showDraftSaved && <p className='saved-text'>Saved.</p>}
              </Col>
              <Col xs={12} md={4}>
                <Button className="mt-3 mb-3" variant='primary' onClick={() => setShowConfirmDataModal(true)} 
              disabled={
                !fixture.appearances || 
                fixture.appearances === 0 || 
                fixture.appearances !== selectedPlayers.homeTeam.length + selectedPlayers.awayTeam.length
            }>
                Save Player Events
            </Button>
              </Col>
            </Row>

          
              <Row>
                <Col xs={12} md={3}>
                  Appearances: {fixture.appearances ? fixture.appearances : 0}
                </Col>
                <Col xs={12} md={3}>
                  Goals: {fixture.goals ? fixture.goals : 0}
                </Col>
                <Col xs={12} md={3}>
                  Assists: {fixture.assists ? fixture.assists : 0}
                </Col>
                <Col xs={12} md={3}>
                  Red Cards: {fixture.redCards ? fixture.redCards : 0}
                </Col>
                <Col xs={12} md={3}>
                  Yellow Cards: {fixture.yellowCards ? fixture.yellowCards : 0}
                </Col>
                <Col xs={12} md={3}>
                  Penalties Missed: {fixture.penaltyMissed ? fixture.penaltyMissed : 0}
                </Col>
                <Col xs={12} md={3}>
                  Penalties Saved: {fixture.penaltySaves ? fixture.penaltySaves : 0}
                </Col>
                <Col xs={12} md={3}>
                  Keeper Saves: {fixture.keeperSaves ? fixture.keeperSaves : 0}
                </Col>
                <Col xs={12} md={3}>
                  Own Goals: {fixture.ownGoals ? fixture.ownGoals : 0}
                </Col>
              </Row>
            <PlayerSelectionModal 
              show={showPlayerSelectionModal} 
              onHide={() => setShowPlayerSelectionModal(false)}
              onPlayersSelected={handlePlayerSelection}
              teamPlayers={teamPlayers}
              selectedTeam={key}
              selectedPlayers={selectedPlayers}
            />
             <PlayerEventsModal 
              show={showPlayerEventModal} 
              onHide={() => setShowPlayerEventModal(false)}
              onPlayerEventAdded={handlePlayerEventAdded}
              playerEventMap={playerEventMap}
              player={editingPlayerEvent}
            />
            
            <ConfirmFixtureDataModal 
              show={showConfirmDataModal} 
              onHide={() => setShowConfirmDataModal(false)}
              onConfirm={handleSaveFixtureData}
            />
            
            <ConfirmClearDraftModal 
              show={showConfirmClearDraftModal} 
              onHide={() => setShowConfirmClearDraftModal(false)}
              onConfirm={handleClearDraft}
            />
          </div>
        </Card.Body>
      </Card>
    </Container>
  );
};

export default PreSNSAddFixtureData;
