// src/OpenFPL_frontend/src/lib/components/fixture-validation/player-events-modal.svelte
<script lang="ts">
  import type { Writable } from "svelte/store";
  import { Modal } from "@dfinity/gix-components";

  export let visible = false;
  export let player: PlayerDTO;
  export let fixtureId: number;
  export let playerEventData: Writable<[] | PlayerEventData[]>;
  export let closeModal: () => void;

  let eventType = -1;
  let eventStartTime = 0;
  let eventEndTime = 0;

  let isSubmitDisabled: boolean = true;
  $: isSubmitDisabled =
    eventType < 0 ||
    eventStartTime < 0 ||
    eventStartTime > 90 ||
    eventEndTime < 0 ||
    eventEndTime > 90;

  const eventOptions = [
    { id: 0, label: "Appearance" },
    { id: 1, label: "Goal Scored" },
    { id: 2, label: "Goal Assisted" },
    { id: 6, label: "Penalty Saved" },
    { id: 7, label: "Penalty Missed" },
    { id: 8, label: "Yellow Card" },
    { id: 9, label: "Red Card" },
    { id: 10, label: "Own Goal" },
  ];

  function handleAddEvent() {
    if (eventType >= 0 && eventStartTime !== null && eventEndTime !== null) {
      const newEvent = {
        playerId: player.id,
        eventType: Number(eventType),
        eventStartMinute: Number(eventStartTime),
        eventEndMinute: Number(eventEndTime),
        fixtureId: fixtureId,
        teamId: player.clubId,
      };
      let updatedEvents: PlayerEventData[] = [...$playerEventData, newEvent];
      playerEventData.set(updatedEvents);
      eventStartTime = 0;
      eventEndTime = 0;
      eventType = -1;
    }
  }

  function handleRemoveEvent(removedEvent: PlayerEventData) {
    playerEventData.update((currentEvents) => {
      return currentEvents.filter(
        (event) =>
          event.playerId != removedEvent.playerId &&
          event.eventStartMinute != removedEvent.eventStartMinute &&
          event.eventEndMinute != removedEvent.eventEndMinute &&
          event.eventType != eventType &&
          event.fixtureId != event.fixtureId &&
          event.clubId != event.clubId
      );
    });
  }

  const getEventTypeLabel = (id: number) => {
    const option = eventOptions.find((option) => option.id === id);
    return option ? option.label : "";
  };
</script>

<Modal {visible} on:nnsClose={closeModal}>
  <div class="p-4">
    <div class="flex justify-between items-center my-2">
      <h4>
        {player.firstName !== "" ? player.firstName.charAt(0) + "." : ""}
        {player.lastName} - Match Events
      </h4>
    </div>

    <div class="mt-4 p-4 border-t border-gray-200">
      <h4>Add Event</h4>
      <div class="flex flex-col gap-1">
        <div class="mt-1">
          <select
            id="eventType"
            bind:value={eventType}
            class="w-full p-2 fpl-dropdown"
          >
            <option value={-1} disabled>Select event type</option>
            <option value={0}>Appearance</option>
            <option value={1}>Goal Scored</option>
            <option value={2}>Goal Assisted</option>
            <option value={7}>Penalty Missed</option>
            <option value={8}>Yellow Card</option>
            <option value={9}> Card</option>
            <option value={10}>Own Goal</option>
            {#if player.position === 0}
              <option value={4}>Keeper Save</option>
              <option value={6}>Penalty Save</option>
            {/if}
          </select>
        </div>
        <div class="mt-1">
          <label for="startMinute" class="block">Start Minute</label>
          <input
            type="number"
            id="startMinute"
            bind:value={eventStartTime}
            class="bg-gray-900 w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Enter start minute"
            min="0"
            max="90"
          />
        </div>
        <div class="mt-2">
          <label for="endMinute" class="block">End Minute</label>
          <input
            type="number"
            id="endMinute"
            bind:value={eventEndTime}
            class="bg-gray-900 w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Enter end minute"
            min="0"
            max="90"
          />
        </div>

        <div class="items-center mt-3 flex space-x-4">
          <button
            class={`${isSubmitDisabled ? "bg-gray-500" : "fpl-purple-btn"} 
            default-button`}
            on:click={handleAddEvent}
            disabled={isSubmitDisabled}>Add Event</button
          >
        </div>
      </div>
    </div>

    <div class="px-4">
      <h4 class="text-sm">Events:</h4>
    </div>
    <div class="mt-1 mx-4">
      <ul class="list-disc">
        {#each $playerEventData.filter((x) => x.playerId == player.id) as event, index}
          <li class="flex justify-between items-center mb-2">
            <span
              >{getEventTypeLabel(event.eventType)} ({event.eventStartMinute} - {event.eventEndMinute})
              mins</span
            >
            <button
              class="default-button bg-red-500"
              on:click={() => handleRemoveEvent(event)}
            >
              Remove
            </button>
          </li>
        {/each}
      </ul>
    </div>

    <div class="items-center mt-3 flex space-x-4">
      <button class="fpl-button default-button fpl-button" on:click={closeModal}
        >Done</button
      >
    </div>
  </div>
</Modal>

// src/OpenFPL_frontend/src/components/governanace/player-events-modal.jsx
import React, { useState, useEffect, useContext } from 'react';
import { Modal, Form, Button, Row, Col, Table } from 'react-bootstrap';

const PlayerEventModal = ({ show, onHide, onPlayerEventAdded, player, playerEventMap  }) => {
    const [playerEvents, setPlayerEvents] = useState([]);
    const [eventType, setEventType] = useState("-1");
    const [eventStartTime, setEventStartTime] = useState("0");
    const [eventEndTime, setEventEndTime] = useState("0");

    useEffect(() => {
        if(!player){
            return;
        }
        const existingEvents = playerEventMap[player.id] || [];
        setPlayerEvents(existingEvents);
        
        setEventType("-1");
        setEventStartTime("0");
        setEventEndTime("0");
    }, [player, playerEventMap]);
    

    const getEventOptions = (position) => {
        const generalOptions = [
            { id: 0, label: 'Appearance' },
            { id: 1, label: 'Goal Scored' },
            { id: 2, label: 'Goal Assisted' },
            { id: 7, label: 'Penalty Missed' },
            { id: 8, label: 'Yellow Card' },
            { id: 9, label: 'Red Card' },
            { id: 10, label: 'Own Goal' }
        ];

        if (position === 0) {
            return [
                ...generalOptions,
                { id: 4, label: 'Keeper Save' },
                { id: 6, label: 'Penalty Saved' }
            ];
        }

        return generalOptions;
    };

    const getEventTypeLabel = (id) => {
        const allOptions = [
            { id: 0, label: 'Appearance' },
            { id: 1, label: 'Goal Scored' },
            { id: 2, label: 'Goal Assisted' },
            { id: 7, label: 'Penalty Missed' },
            { id: 8, label: 'Yellow Card' },
            { id: 9, label: 'Red Card' },
            { id: 10, label: 'Own Goal' },
            { id: 4, label: 'Keeper Save' },
            { id: 6, label: 'Penalty Saved' }
        ];
        const option = allOptions.find(option => option.id === id);
        return option ? option.label : '';
      };

    const handleAddEvent = () => {
        
        if (eventType && eventStartTime !== null && eventEndTime !== null) {
            const newEvent = {
                playerId: player.id,
                eventType: Number(eventType),
                eventStartTime: eventStartTime,
                eventEndTime: eventEndTime
            };
            let updatedEvents = [];
            if (Array.isArray(playerEvents)) {
                updatedEvents = [...playerEvents, newEvent];
            } else {
                updatedEvents = [newEvent];
            }
            setPlayerEvents(updatedEvents);
            onPlayerEventAdded(player.id, updatedEvents);
        }
        setEventStartTime(""); 
        setEventEndTime("");
    };
    
    

    const handleRemoveEvent = (indexToRemove) => {
        const updatedEvents = playerEvents.filter((_, index) => index !== indexToRemove);
        setPlayerEvents(updatedEvents);
        onPlayerEventAdded(player.id, updatedEvents);
    };


    return (
        <Modal show={show} onHide={onHide} centered>
        <Modal.Header closeButton>
            {player && <Modal.Title>{player.firstName != "" ? player.firstName.charAt(0) + "." : ""} {player.lastName} - Match Events</Modal.Title>}
        </Modal.Header>
        <Modal.Body>
            <Form>
                <Form.Group as={Row} className='mb-2'>
                    <Col xs={12}>
                        <Form.Control 
                            as="select"
                            value={eventType}
                            onChange={(e) => {setEventType(e.target.value); setEventStartTime(""); setEventEndTime("");}}>
                                <option value="">Select Event</option>
                                {player && getEventOptions(player.position).map(option => (
                                    <option key={option.id} value={option.id}>
                                        {option.label}
                                    </option>
                                ))}
                        </Form.Control>
                    </Col>
                </Form.Group>
                
                {eventType !== "0" ? (
                <Form.Group as={Row} className='mb-2'>
                            <Col xs={6}>
                            <Form.Control 
                                type="number" 
                                placeholder="Event End Time" 
                                min={0}
                                max={90}
                                value={Number(eventEndTime)}
                                onChange={(e) => {
                                    setEventStartTime(e.target.value);
                                    setEventEndTime(e.target.value);
                                }}
                                />
                            </Col>
                </Form.Group>
                    ) : (
                        <Form.Group as={Row} className='mb-2'>
                            <Col xs={6}>
                            <Form.Control 
                                type="number" 
                                placeholder="Event Start Time" 
                                min={0}
                                max={90}
                                value={Number(eventStartTime)}
                                onChange={(e) => setEventStartTime(e.target.value)}
                                />
                            </Col>
                            <Col xs={6}>
                            <Form.Control 
                                type="number" 
                                placeholder="Event End Time" 
                                min={0}
                                max={90}
                                value={Number(eventEndTime)}   // convert string to number
                                onChange={(e) => setEventEndTime(e.target.value)}
                                />
                            </Col>
                        </Form.Group>
                    )}
                <Form.Group as={Row} className='mb-2'>
                    <Col>
                        <Button className="w-100" onClick={handleAddEvent}>Add Event</Button>
                    </Col>
                </Form.Group>

                <Table responsive bordered className="table-fixed light-table">
                    <thead>
                        <tr>
                            <th>Event Type</th>
                            <th>Start Minute</th>
                            <th>End Minute</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {playerEvents.map((event, index) => (
                            <tr key={index}>
                                <td>{getEventTypeLabel(event.eventType)}</td>
                                <td>{event.eventStartTime}</td>
                                <td>{event.eventEndTime}</td>
                                <td>
                                    <Button onClick={() => handleRemoveEvent(index)}>Remove</Button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </Table>
            </Form>
        </Modal.Body>
        <Modal.Footer>
            <Button variant="primary" onClick={onHide}>
                Done
            </Button>
        </Modal.Footer>
    </Modal>
    );
   
};


export default PlayerEventModal;
