// src/OpenWSL_frontend/src/lib/components/whitepaper/architecture.svelte
<div class="m-4">
  <h1 class="default-header my-4">System Architecture</h1>

  <p class="my-2">
    OpenFPL is a progressive web application, built with Svelte and Motoko. The
    Github is publicly available <a
      class="underline"
      href="github.com/jamesbeadle/openfpl">here</a
    >. OpenFPL's architecture is designed for scalability and efficiency,
    ensuring robust performance even as user numbers grow. Here's how the system
    is structured:
  </p>

  <h2 class="default-sub-header mt-4">Main Backend Canister</h2>
  <p class="my-2">
    OpenFPL' Main Backend Canister stores indexes for a manager's principal and
    canister Id for efficient data retrieval. The Main Backend Canister also
    stores a dictionary of each users principal and username for efficient
    existing username checks.
  </p>
  <p class="my-2">
    The Main Backend canister also stores a list of each unique manager canister
    to enable efficient grouped lookups. Even with 10m users the Main Backend
    Canister only uses 2GB of its available storage, however it is likely that
    the players and user indexes are refactored into their own canisters after
    the SNS sale but before the season starts.
  </p>

  <h2 class="default-sub-header mt-4">Manager Data</h2>
  <p class="my-2">
    A snapshot of a fantasy team is around 147 bytes. So if a manager's players
    for 100 seasons that is a total history of 546 KB (100 x 38 x 147 bytes).
    With the manager's current team, including a 100KB profile picture a manager
    object could take around 646KB of space.
  </p>
  <p class="my-2">
    This means a 96GB canister could theoretically hold around 155,826 managers.
    We divide the canister into 12 partitions and limit the number of managers
    in each partition to 1,000. This gives plenty of storage and calculation
    overhead for future features.
  </p>
  <h2 class="default-sub-header mt-4">Leaderboard Data</h2>
  <p class="my-2">
    A leaderboard canister holds an array of leaderboard entries, with each
    entry taking up roughly 121 bytes of space. This means the leaderboard
    canister can hold over 35m entries within its 4GB heap memory, more than 3
    times the players of the market leading game.
  </p>
</div>

// src/OpenFPL_frontend/src/components/whitepaper/architecture.jsx
import React from 'react';

const Architecture = () => {
  
  return (
    <div className="w-100 px-3">

        <h3 className='mb-4'>Architecture</h3>
        <p className='mb-4'>OpenFPL is being built as a progressive web application, it's curernt frontend is React but will be moved over to Svelte for the start of 2024. The OpenFPL backend is developed in Motoko.
            The Github is publicly available at github.com/jamesbeadle/openfpl.
            OpenFPL's architecture is designed for scalability and efficiency, ensuring robust performance even as user numbers grow. Here's how the system is structured:</p>
        
        <h5>Profile Data</h5>
        
        <p>OpenFPL allocates approximately 254 bytes for a profile record. This means that a single Profile Canister could hold more than 16m profiles, scaling to a size larger than the market leader.</p>
        <p className='mb-4'>Each profile record will hold a reference to the Profile Picture canister where their pfp is stored. We limit the size of profile pictures to 500KB, meaning you can store 8,000 images per Profile Picture canister. When the canister is full, a new Profile Picture canister is created to store the images.</p>        

        <h5>Fantasy Teams Data</h5>
        
        <p className='mb-4'>OpenFPL allocates approximately 913 KB for a fantasy team with a lifetime of seasons history. 
            Therefore we can store over 4,000 fantasy teams in each canister. 
            When this limit is reached, a new canister is created. A reference to the user’s Fantasy Team canister is stored in the user profile record.</p>

        <h5>Leaderboard Data</h5>
        <p className='mb-4'>The size of the leaderboard data is very much dependent on the number of users on the site as each will create an entry in each leaderboard. 
            Therefore we will create a new canister for each leaderboard. 
            For each season there will be a Season Leaderboard canister, 38 Gameweek Leaderboard canisters and 12 Monthly Leaderboard canisters. 
            This architecture will scale to 25m+ users, more than double the players of the market leading platform. </p>

        <h5>Main Canister & Central Data Management</h5>

        <p>Our system estimates the size of the main canister containing data for 100 seasons as around 44MB. 
            With around 1% of the 4GB canister being used, substantial room is available for additional growth and functionalities. 
            The Main canister will contain the following key pieces of information:</p>

        <ul className='mb-4'>
            <li>Data Cache Hashes</li>
            <li>Teams Data</li>
            <li>Seasons Data</li>
            <li>Canister References</li>
        </ul>

        <h5>Player Canisters</h5>

        <p>The player canisters container information on all Premier League football players. OpenFPL allocates approximately 30 KB for each Player record. 
        With a single canister on the Internet Computer boasting a 4GB capacity, it will be able to store 100.000+ Premier League player entries. 
        Each Premier League team could theoretically introduce up to 50 new players per team annually. 
        However, this number implies a complete change of a team's squad, an eventuality that's exceedingly uncommon in the Premier League. 
        Therefore, our projection of 1,000 new players across the league each year offers a deliberately conservative overestimation. 
        Given these calculations, the following 3 canisters will be able to manage all the Premier League players for well over 100 years:</p>        

        <ul>
            <li>Live Players Canister</li>
            <li>Former Players Canister</li>
            <li>Retired Players Canister</li>
        </ul>

        <p className='mb-4'>Players will move from the live canister to and from the Former or Retired players canister when required.</p>

        <h5>Cycle Dispenser</h5>

        <p className='mb-4'>The cycle dispenser canister watches each canister in the OpenFPL ecosystem and tops it up with cycles when it reaches 20% of its top up value.</p>

        <h4>Note on Architecture Evolution and Whitepaper Updates</h4>

        <p>As OpenFPL progresses through the SNS testflight phase, our architecture may undergo changes to optimize performance and scalability. 
            We are committed to staying at the forefront of technological advancements, ensuring that our platform remains robust and efficient.</p>

        <p className='mb-4'>To keep our community and stakeholders informed, any significant changes to the architecture will be reflected in updated versions of this whitepaper. 
            Each new version will be clearly marked to ensure transparency and ease of reference, maintaining our commitment to openness and communication with our users.</p>

    </div>
  );
};

export default Architecture;
