// src/OpenFPL_frontend/src/lib/components/whitepaper/marketing.svelte
<div class="m-4">
  <h1 class="default-header">Marketing</h1>
  <p class="my-4">
    We will be marketing both online and in-person, taking advantage of being
    based in the UK and having access to millions of Premier League fans.
  </p>

  <h2 class="default-header mb-4">Online Marketing Strategy</h2>
  <h2 class="default-header">Collaboration with Digitial Marketing Agency</h2>
  <p class="my-2">
    We are engaging with a digital marketing agency known for their experience
    working with startups in the digital space. This agency is in the process
    of finalising plans for a comprehensive online marketing campaign. The
    campaign will focus on PPC (Pay-Per-Click) and SEO (Search Engine
    Optimisation) strategies, with an emphasis on reaching specific user
    groups effectively.
  </p>

  <h2 class="default-header mt-4">Initial Strategy and Goals</h2>
  <p class="my-2">
    We will have a particular focus on the UK market for initial traction.
    Tracking success through KPIs, focusing on manager sign-ups and event
    attendance.
  </p>

  <h2 class="default-header mt-4">OpenFPL's Initiatives</h2>
  <p class="my-2">
    Our approach is to seamlessly integrate OpenFPL's online marketing
    campaigns with our broader initiatives. A key focus will be on targeted
    local advertising, aiming to highlight the distribution of 200 junior
    football club kits to grassroots football causes across the UK.
    Additionally, we've created a return on investment (ROI) leaderboard for
    each of our NFT collections. This leaderboard will highlight and market
    the clubs that are the most active and supportive in our network. The aim
    is to boost purchases through the ICPFA shop.
  </p>
  <p class="my-2">
    In November 2023, a proposal was passed in the OpenChat DAO for them to
    become the official sponsor of OpenFPL. They will appear on our pick team
    advertising boards along with the football apparel given to grassroots
    football causes and sold through the ICPFA shop. We feel this partnership
    is important as promoting the wide arrange of apps available on the IC
    ecosytem will increase the pace at which the world adopts Internet
    Computer services.
  </p>

  <h2 class="default-header mt-4">Future Considerations</h2>
  <p class="my-2">
    Outside of traditional digital marketing we plan to explore additional
    areas, such as influencer marketing.
  </p>

  <h2 class="default-header">In-Person Event Marketing Strategy</h2>
  <p class="my-2">
    As part of our comprehensive marketing plan, OpenFPL is preparing to
    launch a series of in-person, interactive events in cities home to Premier
    League clubs. These events, expected to start from Q2 2024, are inspired
    by the successful engagement strategies of major UK brands like IBM, Ford
    and Coca-Cola.
  </p>

  <h2 class="default-header mt-4">Event Planning and Execution</h2>
  <p class="my-2">
    We are in discussions with experienced interactive hardware providers and
    event management professionals to assist in creating immersive event
    experiences. We will utilise the expertise of OpenFPL founder, James
    Beadle, in developing and delivering these interactive experiences.
  </p>

  <h2 class="default-header mt-4">Event Objectives and Content</h2>
  <p class="my-2">
    We would like to teach attendees about OpenFPL and the broader Internet
    Computer ecosystem, including Internet Identity and a variety of IC dApps.
    Facilitating hands-on interactions and demonstrations will provide a
    deeper understanding of OpenFPL's features and benefits.
  </p>

  <h2 class="default-header mt-4">Promotion and Community Engagement</h2>
  <p class="my-2">
    We plan to promote these events through targeted local advertising, social
    media campaigns, and collaborations with local football clubs and
    communities. We will encouraging participants to share their experiences
    on social media through various reward scheme, amplifying our reach and
    impact.
  </p>

  <h2 class="default-header mt-4">Long-Term Vision</h2>
  <p class="my-2">
    We will be exploring opportunities to replicate this event model in other
    regions, expanding OpenFPL's global footprint.
  </p>

  <h2 class="default-header mt-4">Overall Approach</h2>
  <p class="my-2">
    The marketing plan aims to be dynamic, adapting to the evolving needs of
    OpenFPL and the response from the target audience. The digital agency and
    OpenFPL will work closely to ensure that the campaigns are coherent,
    data-driven, and aligned with OpenFPL’s overall branding and objectives.
  </p>
</div>

// src/OpenFPL_frontend/src/components/whitepaper/marketing.jsx
import React from 'react';

const Marketing = () => {
  
  return (
    <div className="w-100 px-3">

        <h3 className='mb-4'>Marketing</h3>

        <p className='mb-4'>We will be marketing both online and in-person, 
        taking advantage of being based in the UK and having access to millions of Premier League fans.</p>

        <h4 className='mb-4'>Online Marketing Strategy</h4>

        <h5>Collaboration with Digitial Marketing Agency</h5>
        <p className='mb-4'>We are engaging with a digital marketing agency known for their experience working with startups in the digital space.
            This agency is in the process of finalising plans for a comprehensive online marketing campaign. 
            The campaign will focus on PPC (Pay-Per-Click) and SEO (Search Engine Optimisation) strategies, 
            with an emphasis on reaching specific user groups effectively.
        </p>
        
        <h5>Initial Strategy and Goals</h5>
        <p className='mb-4'>We will have a particular focus on the UK market for initial traction. 
            Tracking success through KPIs, focusing on manager sign-ups and event attendance.
        </p>
                
        <h5>OpenFPL's Initiatives</h5>
        <p>Our approach is to seamlessly integrate OpenFPL's online marketing campaigns with our broader initiatives. 
            A key focus will be on targeted local advertising, aiming to highlight the distribution of 200 junior football club kits to grassroots football causes across the UK.
            Additionally, we've created a return on investment (ROI) leaderboard for each of our NFT collections. 
            This leaderboard will highlight and market the clubs that are the most active and supportive in our network. 
            The aim is to boost purchases through the ICPFA shop.</p>
        <p className='mb-4'>In November 2023, a proposal was passed in the OpenChat DAO for them to become the official sponsor of OpenFPL. They will appear on our pick team advertising boards along 
            with the football apparel given to grassroots football causes and sold through the ICPFA shop. We feel this partnership is important as promoting the wide arrange 
            of apps available on the IC ecosytem will increase the pace at which the world adopts Internet Computer services.
        </p>

        <h5>Future Considerations</h5>
        <p className='mb-4'>Outside of traditional digital marketing we plan to explore additional areas, such as influencer marketing.</p>

        <h4>In-Person Event Marketing Strategy</h4>
      
        <p className='mb-4'>As part of our comprehensive marketing plan, OpenFPL is preparing to launch a series of in-person, interactive events in cities home to Premier League clubs. 
            These events, expected to start from Q2 2024, are inspired by the successful engagement strategies of major UK brands like IBM, Ford and Coca-Cola.</p>

        <h5>Event Planning and Execution</h5>
        
        <p className='mb-4'>We are in discussions with experienced interactive hardware providers and event management professionals to assist in creating immersive event experiences. 
            We will utilise the expertise of OpenFPL founder, James Beadle, in developing and delivering these interactive experiences.
        </p>

        <h5>Event Objectives and Content</h5>

        <p className='mb-4'>
            We would like to teach attendees about OpenFPL and the broader Internet Computer ecosystem, including Internet Identity and a variety of IC dApps.
            Facilitating hands-on interactions and demonstrations will provide a deeper understanding of OpenFPL's features and benefits.
        </p>

        <h5>Promotion and Community Engagement</h5>

        <p className='mb-4'>We plan to promote these events through targeted local advertising, social media campaigns, and collaborations with local football clubs and communities. 
            We will encouraging participants to share their experiences on social media through various reward scheme, amplifying our reach and impact.
        </p>

        <h5>Long-Term Vision</h5>

        <p className='mb-4'>We will be exploring opportunities to replicate this event model in other regions, expanding OpenFPL's global footprint.</p>

        <h5>Overall Approach</h5>
        <p className='mb-4'>The marketing plan aims to be dynamic, adapting to the evolving needs of OpenFPL and the response from the target audience.
            The digital agency and OpenFPL will work closely to ensure that the campaigns are coherent, data-driven, and aligned with OpenFPL’s overall branding and objectives.</p>





    
    </div>
  );
};

export default Marketing;
