// src/OpenFPL_frontend/src/lib/components/whitepaper/revenue.svelte
<div class="m-4">
  <h1 class="default-header">OpenFPL Revenue Streams</h1>
  <p class="my-4">
    OpenFPL's revenue model is thoughtfully designed to sustain and grow the
    DAO while ensuring practical utility and value for its users.
  </p>

  <h2 class="default-header">Diversified Revenue Model</h2>
  <p class="my-2">
    To avoid creating a supply shock by pegging services to a fixed token
    amount, OpenFPL's revenue streams are diversified. This approach mitigates
    the risk of reduced service usage due to infeasibility, ensuring long-term
    stability and utility.
  </p>
  <p class="my-2">
    Revenue streams include Private Leagues, Site Sponsorship, Content
    Creators, Podcasts, and Merchandise. These channels provide a balanced mix
    of $FPL and $ICP revenue, enhancing the DAO's financial resilience.
  </p>

  <h2 class="default-header mt-4">Private Leagues</h2>
  <p class="my-2">
    Private league fees in OpenFPL are charged in ICP to establish a stable
    revenue base. This approach aligns the revenue directly with the number of
    managers, ensuring it scales with user engagement.
  </p>

  <h2 class="default-header mt-4">Merchandise</h2>
  <p class="my-2">
    We have setup a shop at <a
      class="text-blue-500"
      href="https://icpga.org/shop">icpfa.org/shop</a
    > where you will be able to purchase OpenFPL merchandise in FPL or ICP. All
    profits after the promotion, marketing and production of this merchandise will
    be deposited into the DAO's treasury.
  </p>

  <h2 class="default-header">Podcasts</h2>
  <p class="my-2">
    OpenFPL is expanding into podcasting with a main podcast and then various
    club-specific satellite podcasts. Initially hosted off-chain, our
    long-term goal is to transition these to on-chain hosting as services
    become available.
  </p>
  <p class="my-2">
    The main podcast will cover general OpenFPL and football topics, while the
    satellite podcasts will target fans of specific clubs.
  </p>
  <p class="my-2">
    Revenue will be generated from sponsorships and advertising. As our
    listener base grows, these podcasts are expected to become increasingly
    lucrative. All profits, after production costs, will be deposited into the
    DAO's treasury. Beyond revenue, these podcasts are a strategic move to
    bolster community engagement and enhance the OpenFPL brand, providing
    valuable content to our audience.
  </p>

  <h2 class="default-header mt-4">Site Sponsorship</h2>
  <p class="my-2">
    Starting from August 2025, following the conclusion of the sponsorship
    deal with OpenChat, OpenFPL will offer the site sponsorship rights for
    bidding through the DAO. This will open opportunities for interested
    parties to become the named sponsor for an entire season.
  </p>
  <p class="my-2">
    Each year, sponsors can submit their bids to become the main site sponsor
    for the upcoming season, offering any ICRC-1 currency. Once a sponsor is
    selected, their exclusive rights will be secure for the entirety of that
    season. The DAO will not allow further proposals for site sponsorship
    until the subsequent preseason, ensuring the sponsor's exclusive
    visibility and association with OpenFPL.
  </p>
  <p class="my-2">
    All sponsorship revenue will be directed into the DAO's treasury,
    contributing to the financial health and sustainability of OpenFPL.
  </p>

  <h2 class="default-header mt-4">Content Creators</h2>
  <p class="my-2">
    OpenFPL will create a platform for content creators that is designed to
    both empower creators and enhance the utility of the FPL token. Creators
    will produce fantasy football-related content and share it on OpenFPL.
    This content will be available through a video reel format accessible to
    all users.
  </p>
  <p class="my-2">
    For general reel content, creators earn from a pool of FPL tokens,
    allocated based on user likes. Creators can also offer exclusive content
    for subscribers. They will receive 95% of the FPL tokens from these
    subscriptions.
  </p>
  <p class="my-2">
    Subscriptions are purchased exclusively with FPL tokens, enhancing their
    utility. The remaining 5% from subscriptions remains in the DAO's
    treasury. This approach aligns with OpenFPL's commitment to supporting
    content creators, increasing FPL token utility, and rewarding its
    community of neuron holders.
  </p>

  <h2 class="default-header mt-4">Revenue Redistribution Plan</h2>
  <p class="my-2">
    In line with our commitment to directly benefit neuron holders, OpenFPL
    will allocate 50% of any ICRC-1 token received by the DAO each month to
    neuron holders.
  </p>
  <p class="my-2">
    Distribution to neuron holders will be proportional to each neuron's total
    $FPL value and its remaining duration. This ensures a fair and equitable
    redistribution of revenue.
  </p>
  <p class="my-2">
    Calculation for this distribution will be based on the status of FPL
    neurons as at the end of each month, aligning with the DAO's transparent
    and community-focused ethos.
  </p>

  <h2 class="default-header mt-4">Overall Revenue Philosophy</h2>
  <p class="my-2">
    OpenFPL’s revenue philosophy is rooted in creating a sustainable ecosystem
    where the utility token maintains its value and relevance.
  </p>
  <p class="my-2">
    The reinvestment of revenues into the DAO and direct distribution to
    neuron holders are designed to foster a cycle of growth, user engagement,
    and shared prosperity.
  </p>
</div>

// src/OpenFPL_frontend/src/components/whitepaper/revenue.jsx
import React from 'react';

const Revenue = () => {
  
  return (
    <div className="w-100 px-3">

        <h3 className='mb-4'>OpenFPL Revenue Streams</h3>

        <p className='mb-4'>OpenFPL's revenue model is thoughtfully designed to sustain and grow the DAO while ensuring practical utility and value for its users.</p>

        <h5>Diversified Revenue Model</h5>

        <p>To avoid creating a supply shock by pegging services to a fixed token amount, 
            OpenFPL's revenue streams are diversified. This approach mitigates the risk of reduced service usage due to infeasibility, 
            ensuring long-term stability and utility.</p>

        <p className='mb-4'>Revenue streams include Private Leagues, Site Sponsorship, Content Creators, Podcasts, and Merchandise. 
            These channels provide a balanced mix of $FPL and $ICP revenue, enhancing the DAO's financial resilience.</p>

        <h5>Private Leagues</h5>

        <p className='mb-4'>Private league fees in OpenFPL are charged in ICP to establish a stable revenue base. 
            This approach aligns the revenue directly with the number of managers, ensuring it scales with user engagement.</p>

        <h5>Merchandise</h5>
        <p className='mb-4'>We have setup a shop at <a target='_blank' href="https://icpfa.org/shop">icpfa.org/shop</a> where you will be able to purchase OpenFPL merchandise in FPL or ICP. 
            All profits after the promotion, marketing and production of this merchandise will be deposited into the DAO's treasury.</p>

        <h5>Podcasts</h5>
        <p>OpenFPL is expanding into podcasting with a main podcast and then various club-specific satellite podcasts. 
            Initially hosted off-chain, our long-term goal is to transition these to on-chain hosting as services become available.
        </p>

        <p>The main podcast will cover general OpenFPL and football topics, while the satellite podcasts will target fans of specific clubs.</p>

        <p className='mb-4'>Revenue will be generated from sponsorships and advertising. As our listener base grows, these podcasts are expected to become increasingly lucrative. 
            All profits, after production costs, will be deposited into the DAO's treasury. Beyond revenue, these podcasts are a strategic move to bolster community engagement 
            and enhance the OpenFPL brand, providing valuable content to our audience.</p>



        <h5>Site Sponsorship</h5>

        <p>Starting from August 2025, following the conclusion of the sponsorship deal with OpenChat, OpenFPL will offer the site sponsorship rights for bidding through the DAO. 
            This will open opportunities for interested parties to become the named sponsor for an entire season.</p>

        <p>Each year, sponsors can submit their bids to become the main site sponsor for the upcoming season, offering any ICRC-1 currency.
            Once a sponsor is selected, their exclusive rights will be secure for the entirety of that season. 
            The DAO will not allow further proposals for site sponsorship until the subsequent preseason, ensuring the sponsor's exclusive visibility and association with OpenFPL.
        </p>

        <p className='mb-4'>All sponsorship revenue will be directed into the DAO's treasury, contributing to the financial health and sustainability of OpenFPL.</p>

        <h5>Content Creators</h5>

        <p>OpenFPL will create a platform for content creators that is designed to both empower creators and enhance the utility of the FPL token. 
            Creators will produce fantasy football-related content and share it on OpenFPL. This content will be available through a video reel format accessible to all users.</p>

        <p>For general reel content, creators earn from a pool of FPL tokens, allocated based on user likes. Creators can also offer exclusive content for subscribers. 
            They will receive 95% of the FPL tokens from these subscriptions.</p>

        <p className='mb-4'>Subscriptions are purchased exclusively with FPL tokens, enhancing their utility. 
                The remaining 5% from subscriptions remains in the DAO's treasury. This approach aligns with OpenFPL's commitment to supporting content creators, increasing FPL token utility, and rewarding its community of neuron holders.</p>

        <h5>Revenue Redistribution Plan</h5>

        <p>In line with our commitment to directly benefit neuron holders, OpenFPL will allocate 50% of any ICRC-1 token received by the DAO each month to neuron holders.</p>

        <p>Distribution to neuron holders will be proportional to each neuron's total $FPL value and its remaining duration. This ensures a fair and equitable redistribution of revenue.</p>
    
        <p className='mb-4'>Calculation for this distribution will be based on the status of FPL neurons as at the end of each month, aligning with the DAO's transparent and community-focused ethos.</p>

        <h5>Overall Revenue Philosophy</h5>
        <p>OpenFPL’s revenue philosophy is rooted in creating a sustainable ecosystem where the utility token maintains its value and relevance.</p>
        <p className='mb-4'>The reinvestment of revenues into the DAO and direct distribution to neuron holders are designed to foster a cycle of growth, user engagement, and shared prosperity.</p>

    </div>
  );
};

export default Revenue;
