// src/OpenFPL_frontend/src/lib/components/whitepaper/roadmap.svelte
<div class="m-4">
  <h1 class="default-header">Roadmap</h1>
  <p class="my-4">
    We have an ambitious roadmap of features we aim to release:
  </p>
  <h2 class="default-sub-header">November 2023: Investment NFTs Launch</h2>
  <p class="my-2">
    We will be launching 2 NFT collections in November 2024 to give the
    opportunity for users to share in OpenFPL merchandise and podcast revenue.
    These NFTs will be used to fund the production of OpenFPL merchandise
    along with promotion of the OpenFPL platform in the run up to the genesis
    season. Further information can be found in the marketing section of this
    whitepaper.
  </p>

  <h2 class="default-sub-header mt-4">
    December 2023: Svelte Frontend Upgrade
  </h2>
  <p class="my-2">
    We're aligning OpenFPL with flagship IC apps like the NNS, OpenChat & Juno
    by adopting Svelte. This upgrade ensures a consistent user experience and
    leverages Svelte’s server-side rendering for faster load times.
  </p>

  <h2 class="default-sub-header mt-4">
    Jan - Feb 2024: SNS Testflight Testing
  </h2>
  <p class="my-2">
    We will perform comprehensive testing of the OpenFPL gameplay and
    governance features. Detailed descriptions and outcomes of various use
    case tests, demonstrating how gameplay and governance features perform in
    different situations.
  </p>

  <h2 class="default-sub-header mt-4">
    January 2024: 'The OpenFPL Podcast' Launch
  </h2>
  <p class="my-2">
    Starting with a main podcast, we aim to expand into fan-focused podcasts,
    emulating the model of successful platforms like Arsenal Fan TV. Initially
    audio-based, these podcasts will eventually include video content, adding
    another dimension to our engagement strategy.
  </p>

  <h2 class="default-sub-header mt-4">
    January 2024: Shirt Production Begins
  </h2>
  <p class="my-2">
    We are actively engaged in shirt production for OpenFPL, moving beyond
    mere concepts to tangible products. Our collaboration with a UK supplier
    is set to kit out 200 junior clubs with OpenFPL-branded shirts for
    charity, marking our first foray into merging style with the spirit of the
    game. This initiative is further elevated by a successful partnership with
    OpenChat. A recent proposal in the OpenChat DAO has been passed, resulting
    in OpenChat sponsoring half of these shirts, a testament to our
    collaborative efforts and shared vision. Concurrently, we are in advanced
    talks with a manufacturer in India, having already developed a promising
    prototype. We are fine-tuning the details to perfect the shirts, with
    production anticipated to commence in just a few months. Additionally,
    these shirts will be available for sale in the ICPFA shop, with a portion
    of each sale benefiting our NFT holders. This dual approach not only
    strengthens our brand presence but also underscores our commitment to
    supporting grassroots football communities and providing value to our NFT
    investors.
  </p>

  <h2 class="default-sub-header mt-4">
    February 2024: Online Marketing Campaigns
  </h2>
  <p class="my-2">
    We are actively in discussions with a digital marketing agency, preparing
    to launch campaigns aimed at organically growing our base of genuine
    managers. The strategy being formulated focuses on SEO and PPC methods
    aligned with OpenFPL's objectives. These deliberations include choosing
    the most suitable online platforms and crafting a strategy that resonates
    with our ethos. The direction of these campaigns is geared towards
    measurable outcomes, especially in attracting genuine manager sign-ups and
    naturally expanding our online footprint. This approach is designed to
    cultivate a genuine and engaged community, enhancing OpenFPL's presence in
    a manner that's both authentic and impactful.
  </p>

  <h2 class="default-sub-header mt-4">
    March 1st 2024: OpenFPL SNS Decentralisation Sale
  </h2>
  <p class="my-2">
    We aim to begin our decentralisation sale on 1st March 2024, selling 25
    million $FPL tokens (25%).
  </p>

  <h2 class="default-sub-header mt-4">April 2024: Private Leagues</h2>
  <p class="my-2">
    The Private Leagues feature is the start of building your own OpenFPL
    community within the DAO. Managers will be able to create a Private League
    for a fee of 1 $ICP. Managers will have full control over their rewards
    structure, with features such as: Deciding on the entry fee, if any. Any
    entry fee can be in $FPL, $ICP or ckBTC. Deciding on the rewards structure
    currency, amount and percentage payouts per finishing position.
  </p>

  <h2 class="default-sub-header mt-4">April 2024: OpenFPL Events</h2>
  <p class="my-2">
    OpenFPL is set to create a series of interactive experiences at event
    locations in Premier League club cities, drawing inspiration from major UK
    brands like IBM, Ford and Coca-Cola. Planned from Q2 2024 onwards, these
    events will leverage the expertise of OpenFPL founder James Beadle. With
    his experience in creating successful and engaging interactive
    experiences, James aims to play a key role in educating attendees about
    OpenFPL, Internet Identity and the range of other IC dApps available.
  </p>

  <h2 class="default-sub-header mt-4">July 2024: Mobile App Launch</h2>
  <p class="my-2">
    We will release a mobile app shortly before the genesis season begins to
    make OpenFPL more accessible and convenient for users on the go.
  </p>

  <h2 class="default-sub-header mt-4">
    August 2024: OpenFPL Genesis Season Begins
  </h2>
  <p class="my-2">
    In August 2024, we launch our inaugural season, where fantasy teams start
    competing for $FPL rewards on a weekly, monthly and annual basis to
    maximise user engagment.
  </p>

  <h2 class="default-sub-header mt-4">
    November 2024: Content Subscription Launch
  </h2>
  <p class="my-2">
    Partnering with Premier League content creators to offer exclusive
    insights, with a unique monetization model for both free and
    subscription-based content.
  </p>

  <h2 class="default-sub-header mt-4">March 2025: OpenChat Integration</h2>
  <p class="my-2">
    Integrating OpenChat for seamless communication within the OpenFPL
    community, providing updates and increasing engagement through group
    channels.
  </p>

  <h2 class="default-sub-header mt-4">Future: 100% On-Chain AI</h2>
  <p class="my-2">
    At OpenFPL, we are exploring the deployment of a 100% on-chain AI model
    within a dedicated canister. Our initial use case for this AI would be to
    integrate a feature within the team selection interface, allowing users to
    receive AI-recommended changes. Users will then have the option to review
    and decide whether to implement these AI suggestions in their team
    management decisions. However, given that the Internet Computer's
    infrastructure is still evolving, especially in terms of on-chain training
    capabilities, our immediate strategy involves training the model
    off-chain. As the IC infrastructure evolves we would look to transition to
    real-time, continual learning for the AI model directly on the IC. Looking
    ahead, we're excited about the potential to develop new models using our
    constantly expanding on-chain dataset, opening up more innovative
    possibilities for OpenFPL.
  </p>
</div>

// src/OpenFPL_frontend/src/components/whitepaper/roadmap.jsx
import React from 'react';

const Roadmap = () => {
  
  return (
    <div className="w-100 px-3">
        
        <h3 className='mb-4'>Roadmap</h3>

        <p className='mb-4'>We have an ambitious roadmap of features we aim to release:</p>

        <h5><b>November 2023: </b>Investment NFTs Launch</h5>
        <p className='mb-4'>
            We will be launching 2 NFT collections in November 2024 to give the opportunity for users to share in OpenFPL merchandise and podcast revenue. 
            These NFTs will be used to fund the production of OpenFPL merchandise along with promotion of the OpenFPL platform in the run up to the genesis season.
            Further information can be found in the marketing section of this whitepaper.
        </p>
        
        <h5><b>December 2023: </b>Svelte Frontend Upgrade</h5>
        <p className='mb-4'>We're aligning OpenFPL with flagship IC apps like the NNS, OpenChat & Juno by adopting Svelte. 
            This upgrade ensures a consistent user experience and leverages Svelte’s server-side rendering for faster load times.
        </p>
        
        <h5><b>Jan - Feb 2024: </b>SNS Testflight Testing</h5>
        <p className='mb-4'>We will perform comprehensive testing of the OpenFPL gameplay and governance features. 
            Detailed descriptions and outcomes of various use case tests, demonstrating how gameplay and governance features perform in different situations.</p>
                
        <h5><b>January 2024: </b>'The OpenFPL Podcast' Launch</h5>
        <p>Starting with a main podcast, we aim to expand into fan-focused podcasts, emulating the model of successful platforms like Arsenal Fan TV. 
            Initially audio-based, these podcasts will eventually include video content, adding another dimension to our engagement strategy.
        </p>

        <h5><b>January 2024: </b>Shirt Production Begins</h5>
        <p className='mb-4'>We are actively engaged in shirt production for OpenFPL, moving beyond mere concepts to tangible products. Our collaboration with a UK supplier is set to kit out 200 junior clubs with OpenFPL-branded shirts for charity, marking our first foray into merging style with the spirit of the game. This initiative is further elevated by a successful partnership with OpenChat. A recent proposal in the OpenChat DAO has been passed, resulting in OpenChat sponsoring half of these shirts, a testament to our collaborative efforts and shared vision.
            Concurrently, we are in advanced talks with a manufacturer in India, having already developed a promising prototype. We are fine-tuning the details to perfect the shirts, with production anticipated to commence in just a few months.
            Additionally, these shirts will be available for sale in the ICPFA shop, with a portion of each sale benefiting our NFT holders. This dual approach not only strengthens our brand presence but also underscores our commitment to supporting grassroots football communities and providing value to our NFT investors.
        </p>
        
        <h5><b>February 2024: </b>Online Marketing Campaigns</h5>
        <p className='mb-4'>We are actively in discussions with a digital marketing agency, preparing to launch campaigns aimed at organically growing our base of genuine managers. 
            The strategy being formulated focuses on SEO and PPC methods aligned with OpenFPL's objectives. 
            These deliberations include choosing the most suitable online platforms and crafting a strategy that resonates with our ethos.
            The direction of these campaigns is geared towards measurable outcomes, especially in attracting genuine manager sign-ups and naturally expanding our online footprint. 
            This approach is designed to cultivate a genuine and engaged community, enhancing OpenFPL's presence in a manner that's both authentic and impactful.</p>
        

        <h5><b>March 1st 2024: </b>OpenFPL SNS Decentralisation Sale</h5>
        <p className='mb-4'>We aim to begin our decentralisation sale on 1st March 2024, selling 25 million $FPL tokens (25%).</p>


        <h5><b>April 2024: </b>Private Leagues</h5>
        <p>The Private Leagues feature is the start of building your own OpenFPL community within the DAO. Managers will be able to create a Private League for a fee of 1 $ICP. Managers will have full control over their rewards structure, with features such as:
            Deciding on the entry fee, if any. Any entry fee can be in $FPL, $ICP or ckBTC.
            Deciding on the rewards structure currency, amount and percentage payouts per finishing position.</p>
        

        <h5><b>April 2024: </b>OpenFPL Events</h5>
        <p className='mb-4'>
            OpenFPL is set to create a series of interactive experiences at event locations in Premier League club cities, drawing inspiration from major UK brands like IBM, Ford and Coca-Cola. 
            Planned from Q2 2024 onwards, these events will leverage the expertise of OpenFPL founder James Beadle. With his experience in creating successful and engaging interactive experiences, 
            James aims to play a key role in educating attendees about OpenFPL, Internet Identity and the range of other IC dApps available.
        </p>
        
        <h5><b>July 2024: </b>Mobile App Launch</h5>
        <p className='mb-4'>We will release a mobile app shortly before the genesis season begins to make OpenFPL more accessible and convenient for users on the go.</p>
                
        <h5><b>August 2024: </b>OpenFPL Genesis Season Begins</h5>

        <p className='mb-4'>In August 2024, we launch our inaugural season, where fantasy teams start competing for $FPL rewards on a weekly, monthly and annual basis to maximise user engagment.</p>

        <h5><b>November 2024: </b>Content Subscription Launch</h5>
        <p className='mb-4'>Partnering with Premier League content creators to offer exclusive insights, with a unique monetization model for both free and subscription-based content.</p>
        
        <h5><b>March 2025: </b>OpenChat Integration</h5>
        <p>Integrating OpenChat for seamless communication within the OpenFPL community, providing updates and increasing engagement through group channels.</p>
        
        <h5><b>Future: </b>100% On-Chain AI</h5>
        <p className='mb-4'>At OpenFPL, we are exploring the deployment of a 100% on-chain AI model within a dedicated canister. 
            Our initial use case for this AI would be to integrate a feature within the team selection interface, allowing users to receive AI-recommended changes. 
            Users will then have the option to review and decide whether to implement these AI suggestions in their team management decisions.
            However, given that the Internet Computer's infrastructure is still evolving, especially in terms of on-chain training capabilities, 
            our immediate strategy involves training the model off-chain. As the IC infrastructure evolves we would look to transition to real-time, 
            continual learning for the AI model directly on the IC. 
            Looking ahead, we're excited about the potential to develop new models using our constantly expanding on-chain dataset, opening up more innovative possibilities for OpenFPL.</p>
    
    
    </div>
  );
};

export default Roadmap;
