// src/OpenFPL_frontend/src/lib/components/whitepaper/vision.svelte
<div class="container-fluid mx-auto p-4">
  <div class="m-4">
    <h1 class="default-header">Our Vision</h1>
    <p class="my-4">
      In an evolving landscape where blockchain technology is still unlocking
      its potential, the Internet Computer offers a promising platform for
      innovative applications. OpenFPL is one such initiative, aiming to
      transform fantasy Premier League football into a more engaging and
      decentralised experience.
    </p>
    <p class="my-4">
      Our goal is to develop this popular service into a decentralised
      autonomous organisation (DAO), rewarding fans for their insight and
      participation in football.
    </p>
    <p class="my-4">
      Our vision for OpenFPL encompasses a commitment to societal impact,
      specifically through meaningful contributions to the ICPFA community fund.
      This effort is focused on supporting grassroots football initiatives,
      demonstrating our belief in OpenFPL's ability to bring about positive
      change in the football community.
    </p>
    <p class="my-4">
      OpenFPL aims to be recognised as more than just a digital platform; we
      aspire to build a brand that creates diverse revenue opportunities. Our
      economic model is designed to directly benefit our token holders,
      particularly those with staked neurons, through a fair distribution of
      rewards. This ensures that the value generated by the platform is shared
      within our community.
    </p>
    <p class="my-4">
      Central to OpenFPL is our community focus. We strive to create a space
      where Premier League fans feel at home, with their input shaping the
      service. Our features, including community-based player valuations,
      customisable private leagues, and collaborations with football content
      creators, are all aimed at enhancing user engagement. As we attract more
      users, we expect an increased demand for our services, which will
      contribute to the growth and value of our governance token, $FPL.
    </p>
    <p class="my-4">
      In essence, OpenFPL represents a unique blend of football passion and
      blockchain innovation. Our approach is about more than just reinventing
      fantasy sports; it's about building a vibrant community, pushing
      technological boundaries, and generating new economic opportunities.
      OpenFPL seeks to redefine the way fans engage with the sport they love,
      making a real impact in the football world.
    </p>
    <p class="my-4">
      Innovation is at the heart of OpenFPL. We are excited about exploring the
      possibilities of integrating on-chain AI to assist managers with team
      selection. This endeavor is not just about enhancing the user experience;
      it's about exploring new frontiers for blockchain technology in sports.
    </p>
  </div>
</div>

// src/OpenFPL_frontend/src/components/whitepaper/vision.jsx
import React from 'react';

const Vision = () => {
  
  return (
    <div className="w-100 px-3">

      <h3 className='mb-4'>Our Vision</h3>
      
      <p>In an evolving landscape where blockchain technology is still unlocking its potential, the Internet Computer offers a promising platform for innovative applications. 
        OpenFPL is one such initiative, aiming to transform fantasy Premier League football into a more engaging and decentralised experience.
      </p>
      
      <p>Our goal is to develop this popular service into a decentralised autonomous organisation (DAO), rewarding fans for their insight and participation in football.</p>
      
      <p>Our vision for OpenFPL encompasses a commitment to societal impact, specifically through meaningful contributions to the ICPFA community fund. 
        This effort is focused on supporting grassroots football initiatives, demonstrating our belief in OpenFPL's ability to bring about positive change in the football community.</p>

      <p>OpenFPL aims to be recognised as more than just a digital platform; we aspire to build a brand that creates diverse revenue opportunities. 
        Our economic model is designed to directly benefit our token holders, particularly those with staked neurons, through a fair distribution of rewards. 
        This ensures that the value generated by the platform is shared within our community.</p>

      <p>Central to OpenFPL is our community focus. We strive to create a space where Premier League fans feel at home, with their input shaping the service. 
        Our features, including community-based player valuations, customisable private leagues, and collaborations with football content creators, are all aimed at enhancing user engagement. 
        As we attract more users, we expect an increased demand for our services, which will contribute to the growth and value of our governance token, $FPL.</p>

      <p>In essence, OpenFPL represents a unique blend of football passion and blockchain innovation. 
        Our approach is about more than just reinventing fantasy sports; it's about building a vibrant community, pushing technological boundaries, and generating new economic opportunities. 
        OpenFPL seeks to redefine the way fans engage with the sport they love, making a real impact in the football world.</p>
      
      <p>Innovation is at the heart of OpenFPL. We are excited about exploring the possibilities of integrating on-chain AI to assist managers with team selection. 
        This endeavor is not just about enhancing the user experience; it's about exploring new frontiers for blockchain technology in sports.</p>
    </div>
  );
};

export default Vision;
