// src/OpenFPL_frontend/src/lib/components/fixtures.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import BadgeIcon from "$lib/icons/BadgeIcon.svelte";
  import type { Team } from "../../../../declarations/OpenFPL_backend/OpenFPL_backend.did";
  import { SystemService } from "$lib/services/SystemService";
  import { FixtureService } from "$lib/services/FixtureService";
  import { TeamService } from "$lib/services/TeamService";
  import type { FixtureWithTeams } from "$lib/types/FixtureWithTeams";
  import { formatUnixTimeToTime } from "../utils/Helpers";

  const fixtureService = new FixtureService();
  const teamService = new TeamService();
  const systemService = new SystemService();

  let selectedGameweek: number = 1;
  let fixtures: FixtureWithTeams[] = [];
  let teams: Team[] = [];
  let gameweeks = Array.from({ length: 38 }, (_, i) => i + 1);
  $: filteredFixtures = fixtures.filter(
    ({ fixture }) => fixture.gameweek === selectedGameweek
  );

  $: groupedFixtures = filteredFixtures.reduce(
    (acc: { [key: string]: FixtureWithTeams[] }, fixtureWithTeams) => {
      const date = new Date(Number(fixtureWithTeams.fixture.kickOff) / 1000000);
      const dateFormatter = new Intl.DateTimeFormat("en-GB", {
        weekday: "long",
        day: "numeric",
        month: "long",
        year: "numeric",
      });
      const dateKey = dateFormatter.format(date);

      if (!acc[dateKey]) {
        acc[dateKey] = [];
      }
      acc[dateKey].push(fixtureWithTeams);
      return acc;
    },
    {} as { [key: string]: FixtureWithTeams[] }
  );

  onMount(async () => {
    try {
      await systemService.updateSystemStateData();
      await fixtureService.updateFixturesData();
      await teamService.updateTeamsData();
      const fetchedFixtures = await fixtureService.getFixtures();
      const fetchedTeams = await teamService.getTeams();

      teams = fetchedTeams;
      fixtures = fetchedFixtures.map((fixture) => ({
        fixture,
        homeTeam: getTeamFromId(fixture.homeTeamId),
        awayTeam: getTeamFromId(fixture.awayTeamId),
      }));
      let systemState = await systemService.getSystemState();
      selectedGameweek = systemState?.activeGameweek ?? selectedGameweek;
    } catch (error) {
      console.error("Error fetching data:", error);
    }
  });

  const changeGameweek = (delta: number) => {
    selectedGameweek = Math.max(1, Math.min(38, selectedGameweek + delta));
  };

  function getTeamFromId(teamId: number): Team | undefined {
    return teams.find((team) => team.id === teamId);
  }
</script>

<div class="container-fluid mt-4">
  <div class="flex flex-col space-y-4">
    <div class="flex flex-col sm:flex-row gap-4 sm:gap-8">
      <div class="flex items-center space-x-2 ml-4">
        <button
          class="text-2xl rounded fpl-button px-3 py-1"
          on:click={() => changeGameweek(-1)}
          disabled={selectedGameweek === 1}
        >
          &lt;
        </button>

        <select
          class="p-2 fpl-dropdown text-sm md:text-xl text-center"
          bind:value={selectedGameweek}
        >
          {#each gameweeks as gameweek}
            <option value={gameweek}>Gameweek {gameweek}</option>
          {/each}
        </select>

        <button
          class="text-2xl rounded fpl-button px-3 py-1 ml-1"
          on:click={() => changeGameweek(1)}
          disabled={selectedGameweek === 38}
        >
          &gt;
        </button>
      </div>
    </div>
    <div>
      {#each Object.entries(groupedFixtures) as [date, fixtures]}
        <div>
          <div
            class="flex items-center justify-between border border-gray-700 py-4 bg-light-gray"
          >
            <h2 class="date-header ml-4 text-xs md:text-lg">{date}</h2>
          </div>
          {#each fixtures as { fixture, homeTeam, awayTeam }}
            <div
              class={`flex items-center justify-between py-2 border-b border-gray-700  ${
                fixture.status === 0 ? "text-gray-400" : "text-white"
              }`}
            >
              <div class="flex items-center w-1/2 ml-4">
                <div class="flex w-1/2 space-x-4 justify-center">
                  <div class="w-10 items-center justify-center">
                    <a href={`/club?id=${fixture.homeTeamId}`}>
                      <BadgeIcon
                        primaryColour={homeTeam
                          ? homeTeam.primaryColourHex
                          : ""}
                        secondaryColour={homeTeam
                          ? homeTeam.secondaryColourHex
                          : ""}
                        thirdColour={homeTeam ? homeTeam.thirdColourHex : ""}
                      />
                    </a>
                  </div>
                  <span class="font-bold text-lg">v</span>
                  <div class="w-10 items-center justify-center">
                    <a href={`/club?id=${fixture.awayTeamId}`}>
                      <BadgeIcon
                        primaryColour={awayTeam
                          ? awayTeam.primaryColourHex
                          : ""}
                        secondaryColour={awayTeam
                          ? awayTeam.secondaryColourHex
                          : ""}
                        thirdColour={awayTeam ? awayTeam.thirdColourHex : ""}
                      />
                    </a>
                  </div>
                </div>
                <div class="flex w-1/2 md:justify-center">
                  <span class="text-sm md:text-lg ml-4 md:ml-0 text-left"
                    >{formatUnixTimeToTime(Number(fixture.kickOff))}</span
                  >
                </div>
              </div>
              <div class="flex items-center space-x-10 w-1/2 md:justify-center">
                <div
                  class="flex flex-col min-w-[120px] md:min-w-[300px] text-xs md:text-lg"
                >
                  <a href={`/club?id=${fixture.homeTeamId}`}
                    >{homeTeam ? homeTeam.friendlyName : ""}</a
                  >
                  <a href={`/club?id=${fixture.awayTeamId}`}
                    >{awayTeam ? awayTeam.friendlyName : ""}</a
                  >
                </div>
                <div
                  class="flex flex-col min-w-[120px] md:min-w-[300px] text-xs md:text-lg"
                >
                  <span>{fixture.status === 0 ? "-" : fixture.homeGoals}</span>
                  <span>{fixture.status === 0 ? "-" : fixture.awayGoals}</span>
                </div>
              </div>
            </div>
          {/each}
        </div>
      {/each}
    </div>
  </div>
</div>

// src/OpenFPL_frontend/src/components/fixtures.jsx
import React, { useState, useEffect, useContext } from 'react';
import { Container, Row, Col, Card, Button, Spinner } from 'react-bootstrap';
import { DataContext } from "../contexts/DataContext";
import { getTeamById,groupFixturesByDate, computeTimeLeft } from './helpers';
import { BadgeIcon, ClockIcon, ArrowLeft, ArrowRight } from './icons';

const Fixtures = () => {
  const { teams, seasons, fixtures, systemState } = useContext(DataContext);
  const [isLoading, setIsLoading] = useState(true);
  const [currentGameweek, setCurrentGameweek] = useState(systemState.activeGameweek);
  const [currentSeason, setCurrentSeason] = useState(systemState.activeSeason);
  const [filteredFixtures, setFilteredFixtures] = useState([]);
  const [fetchedFixtures, setFetchedFixtures] = useState(null); 
  
  useEffect(() => {
    const fetchData = async () => {
      await fetchViewData();
      setIsLoading(false);
    };
    fetchData();
  }, []);
  
  const fetchViewData = async () => {
  
    const currentDateTime = new Date();
    const currentGameweekFixtures = fixtures.filter(fixture => fixture.gameweek === systemState.activeGameweek);
    currentGameweekFixtures.sort((a, b) => Number(a.kickOff) - Number(b.kickOff));

    const kickOffInMilliseconds = Number(currentGameweekFixtures[0].kickOff) / 1000000;
    const firstFixtureTime = new Date(kickOffInMilliseconds);
   
    const oneHourBeforeFirstFixture = new Date(firstFixtureTime - 3600000);
   
    if (currentDateTime >= oneHourBeforeFirstFixture) {
        setCurrentGameweek(systemState.activeGameweek + 1);
    }
    else{
      setCurrentGameweek(systemState.activeGameweek);  
    }
  };

  useEffect(() => {
    const source = fetchedFixtures || fixtures;
    const filteredFixturesData = source.filter(fixture => fixture.gameweek === currentGameweek);
    setFilteredFixtures(groupFixturesByDate(filteredFixturesData));
  }, [fixtures, currentGameweek, fetchedFixtures]);

  const handleGameweekChange = (change) => {
    setCurrentGameweek(prev => Math.min(38, Math.max(1, prev + change)));
  };
  
  const handleSeasonChange = async (change) => {
    const newIndex = seasons.findIndex(season => season.id === currentSeason.id) + change;
    if (newIndex >= 0 && newIndex < seasons.length) {
      setCurrentSeason(seasons[newIndex]);
      setCurrentGameweek(1);
      
      if (seasons[newIndex].id !== systemState.activeSeason.id) {
        const newFixtures = await fetchFixturesForSeason(seasons[newIndex].id);
        setFetchedFixtures(newFixtures);
      } else {
        setFetchedFixtures(null);
      }
    }
  };
  
  const fetchFixturesForSeason = async (seasonId) => {
    try{
      return await open_fpl_backend.getFixturesForSeason(seasonId);
    }
    catch (error){
      console.log(error);
    }
  };
    
  const renderStatusBadge = (fixture) => {
    const currentTime = new Date().getTime();
    const kickoffTime = computeTimeLeft(Number(fixture.kickOff));
    const oneHourInMilliseconds = 3600000;

    if (fixture.status === 0 && kickoffTime - currentTime <= oneHourInMilliseconds) {
        return (
            <p className="status-text pregame">Pre-Game</p>
        );
    }

    switch (fixture.status) {
        case 1:
            return (
              <p className="status-text fixture-active">Active</p>
            );
        case 2:
            return (
              <p className="status-text fixture-consensus">In Consensus</p>
            );
        case 3:
            return (
              <p className="status-text fixture-verified">Verified</p>
            );
    }
    return (<p className="status-text fixture-unplayed">Unplayed</p>
    );
  };
  
  
  return (
      <>
        {isLoading ? (
          <div className="d-flex flex-column align-items-center justify-content-center">
            <Spinner animation="border" />
            <p className='text-center mt-1'>Loading Fixtures</p>
          </div>) 
          :
          <div className="dark-tab-row w-100 mx-0">
            <Row>
              <Col md={12}>
                <div className='filter-row' style={{ display: 'flex', justifyContent: 'left', alignItems: 'left' }}>
                  <div style={{ display: 'flex', alignItems: 'center' }}>
                    <Button className="w-100 justify-content-center fpl-btn" onClick={() => handleGameweekChange(-1)} disabled={currentGameweek === 1}
                      style={{ marginRight: '16px' }} >
                      <ArrowLeft />
                    </Button>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center' }}>
                    <small>Gameweek {currentGameweek}</small>
                  </div>
                  <div style={{display: 'flex', alignItems: 'center', marginRight: 50}}>
                    <Button className="w-100 justify-content-center fpl-btn" onClick={() => handleGameweekChange(1)} disabled={currentGameweek === 38}
                      style={{ marginLeft: '16px' }} >
                      <ArrowRight />
                    </Button>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center' }}>
                    <Button className="w-100 justify-content-center fpl-btn"  onClick={() => handleSeasonChange(-1)} disabled={currentSeason.id === seasons[0].id} 
                      style={{ marginRight: '16px' }} >
                      <ArrowLeft />
                    </Button>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center' }}>
                    <small>{currentSeason.name}</small>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', marginRight: 50 }}>
                    <Button className="w-100 justify-content-center fpl-btn"  onClick={() => handleSeasonChange(1)} disabled={currentSeason.id === seasons[seasons.length - 1].id} 
                      style={{ marginLeft: '16px' }} >
                      <ArrowRight />
                    </Button>
                  </div>
                </div>
              </Col>
            </Row>

            <Row>
              {Object.entries(filteredFixtures).map(([date, fixturesForDate], dateIdx) => {
                return (
                    <Container key={dateIdx}>
                      <Row>
                        <Col xs={12}>
                          <div className='light-background date-row w-100'  style={{ display: 'flex', alignItems: 'center' }}>
                            <p className="w-100 date-header">{date}</p>
                          </div>
                        </Col>  
                      </Row>
                        
                        {fixturesForDate.map((fixture, idx) => {
                            const homeTeam = getTeamById(teams, fixture.homeTeamId);
                            const awayTeam = getTeamById(teams, fixture.awayTeamId);
                            if (!homeTeam || !awayTeam) {
                                console.error("One of the teams is missing for fixture: ", fixture);
                                return null;
                            }
                            return (
                              <div className="table-row" key={fixture.id}>
                                <div className="col-home-team">
                                  <p className='fixture-team-name'>
                                            <BadgeIcon
                                                primaryColour={'#123432'}
                                                secondaryColour={'#432123'}
                                                thirdColour={'#432123'}
                                                width={48}
                                                height={48}
                                                marginRight={16}
                                            />
                                          {getTeamById(teams, fixture.homeTeamId).friendlyName}
                                    </p>
                                </div>
                                <div className="col-vs">
                                  <p className="w-100 text-center">vs</p>
                                </div>
                                <div className="col-away-team">
                                  <p className='fixture-team-name'>
                                    <BadgeIcon
                                          primaryColour={'#123432'}
                                          secondaryColour={'#432123'}
                                          thirdColour={'#432123'}
                                          width={48}
                                          height={48}
                                          marginRight={16}
                                      />
                                    {getTeamById(teams, fixture.awayTeamId).friendlyName}</p>
                                </div>
                                <div className="col-time">
                                <p>
                                  <ClockIcon
                                                primaryColour={'#123432'}
                                                secondaryColour={'#432123'}
                                                thirdColour={'#432123'}
                                                marginRight={10}
                                                width={20}
                                                height={20}
                                            /> 05:30AM</p>
                                </div>
                                  <div className="col-badge">
                                {renderStatusBadge(fixture)}
                               </div>
                              </div>
                            );
                        })}
                    </Container>
                );
              })}

            </Row>
          </div>
      }
      </>
  );
};

export default Fixtures;
