// src/OpenFPL_frontend/src/lib/components/league-table.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { toastStore } from "$lib/stores/toast-store";
  import { teamStore } from "$lib/stores/team-store";
  import { fixtureStore } from "$lib/stores/fixture-store";
  import { systemStore } from "$lib/stores/system-store";
  import BadgeIcon from "$lib/icons/BadgeIcon.svelte";
  import { updateTableData } from "../utils/Helpers";
  import type {SystemState, Team } from "../../../../declarations/OpenFPL_backend/OpenFPL_backend.did";
  import type { FixtureWithTeams } from "$lib/types/FixtureWithTeams";
  import type { Fixture } from "../../../../declarations/player_canister/player_canister.did";

  let teams: Team[] = [];
  let fixtures: Fixture[] = [];
  let systemState: SystemState | null;
  let fixturesWithTeams: FixtureWithTeams[] = [];
  let selectedGameweek: number = 1;
  let gameweeks = Array.from({ length: 38 }, (_, i) => i + 1);
  let tableData: any[] = [];

  let unsubscribeTeams: () => void;
  let unsubscribeFixtures: () => void;
  let unsubscribeSystemState: () => void;

  onMount(async () => {
    try{
      teamStore.sync();
      fixtureStore.sync();
      systemStore.sync();

      unsubscribeTeams = teamStore.subscribe((value) => {
        teams = value;
      });

      unsubscribeFixtures = fixtureStore.subscribe((value) => {
        fixtures = value;
        fixturesWithTeams = fixtures.map((fixture) => ({
          fixture,
          homeTeam: getTeamFromId(fixture.homeTeamId),
          awayTeam: getTeamFromId(fixture.awayTeamId),
        }));
      });

      unsubscribeSystemState = systemStore.subscribe((value) => {
        systemState = value;
      });
      
    } catch(error){
      toastStore.show("Error fetching league table.", "error");
      console.error("Error fetching league table:", error);
    } finally{}
  });
  
  onDestroy(() => {
    unsubscribeTeams?.();
    unsubscribeFixtures?.();
    unsubscribeSystemState?.();
  });

  $: if (fixtures.length > 0 && teams.length > 0) {
    tableData = updateTableData(fixturesWithTeams, teams, selectedGameweek);
  }

  const changeGameweek = (delta: number) => {
    selectedGameweek = Math.max(1, Math.min(38, selectedGameweek + delta));
  };

  function getTeamFromId(teamId: number): Team | undefined {
    return teams.find((team) => team.id === teamId);
  }
</script>

<div class="container-fluid mt-4">
  <div class="flex flex-col sm:flex-row gap-4 sm:gap-8">
    <div class="flex items-center space-x-2 ml-4">
      <button
        class="text-2xl rounded fpl-button px-3 py-1"
        on:click={() => changeGameweek(-1)}
        disabled={selectedGameweek === 1}
      >
        &lt;
      </button>

      <select
        class="p-2 fpl-dropdown text-sm md:text-xl text-center"
        bind:value={selectedGameweek}
      >
        {#each gameweeks as gameweek}
          <option value={gameweek}>Gameweek {gameweek}</option>
        {/each}
      </select>

      <button
        class="text-2xl rounded fpl-button px-3 py-1 ml-1"
        on:click={() => changeGameweek(1)}
        disabled={selectedGameweek === 38}
      >
        &gt;
      </button>
    </div>
  </div>

  <div class="flex flex-col space-y-4 mt-4 text-lg">
    <div class="overflow-x-auto flex-1">
      <div
        class="flex justify-between p-2 border border-gray-700 py-4 bg-light-gray"
      >
        <div class="w-1/12 text-center mx-4">Pos</div>
        <div class="w-3/12">Team</div>
        <div class="w-1/12 text-center">P</div>
        <div class="w-1/12 text-center">W</div>
        <div class="w-1/12 text-center">D</div>
        <div class="w-1/12 text-center">L</div>
        <div class="w-1/12 text-center">GF</div>
        <div class="w-1/12 text-center">GA</div>
        <div class="w-1/12 text-center">GD</div>
        <div class="w-1/12 text-center">PTS</div>
      </div>

      {#each tableData as team, idx}
        <div
          class="flex items-center justify-between py-4 border-b border-gray-700 cursor-pointer"
        >
          <div class="w-1/12 text-center mx-4">{idx + 1}</div>
          <a
            class="w-3/12 flex items-center justify-start"
            href={`/club?id=${team.id}`}
          >
            <BadgeIcon
              primaryColour={team.primaryColourHex}
              secondaryColour={team.secondaryColourHex}
              thirdColour={team.thirdColourHex}
              className="w-6 h-6 mr-2"
            />
            {team.friendlyName}
          </a>
          <div class="w-1/12 text-center">{team.played}</div>
          <div class="w-1/12 text-center">{team.wins}</div>
          <div class="w-1/12 text-center">{team.draws}</div>
          <div class="w-1/12 text-center">{team.losses}</div>
          <div class="w-1/12 text-center">{team.goalsFor}</div>
          <div class="w-1/12 text-center">{team.goalsAgainst}</div>
          <div class="w-1/12 text-center">
            {team.goalsFor - team.goalsAgainst}
          </div>
          <div class="w-1/12 text-center">{team.points}</div>
        </div>
      {/each}
    </div>
  </div>
</div>

// src/OpenFPL_frontend/src/components/league-table.jsx
import React, { useState, useEffect, useContext } from 'react';
import { Form, Spinner, Container, Card, Row, Col } from 'react-bootstrap';
import { LinkContainer } from 'react-router-bootstrap';
import { OpenFPL_backend as open_fpl_backend } from '../../../declarations/OpenFPL_backend';
import { TeamsContext } from "../contexts/TeamsContext";

const LeagueTable = ({ columns }) => {
    const { teams } = useContext(TeamsContext);
    const [isLoading, setIsLoading] = useState(true);
    const [seasons, setSeasons] = useState([]);
    const [selectedSeason, setSelectedSeason] = useState(1);
    const [selectedGameweek, setSelectedGameweek] = useState(1);
    const [tableData, setTableData] = useState([]);
    const defaultColumns = [
        'Pos', 'Team', 'P', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts'
    ];
    const activeColumns = columns || defaultColumns;
    const [fixtures, setFixtures] = useState([]);

    useEffect(() => {
        const fetchData = async () => {
            await fetchSeasons();
            await fetchFixtures();
            const activeSeasonData = await fetchActiveSeasonId();
            const activeGameweekData = await fetchActiveGameweek();
            setSelectedSeason(activeSeasonData);
            setSelectedGameweek(activeGameweekData);
            setIsLoading(false);
        };
        fetchData();
    }, []);

    useEffect(() => {
        
        if(fixtures.length == 0){
            return;
        }
        updateTableData();
    }, [selectedSeason, selectedGameweek, fixtures]);

    
    const fetchFixtures = async () => {
        const fixturesData = await open_fpl_backend.getFixtures();
        
        setFixtures(fixturesData);
    };

    const fetchActiveGameweek = async () => {
        try {
            const activeGameweekData = await open_fpl_backend.getCurrentGameweek();
            return activeGameweekData;
        } catch(error) {
            console.error("Error fetching active gameweek: ", error);
        }
    };
    
    const fetchActiveSeasonId = async () => {
        const activeSeasonData = await open_fpl_backend.getCurrentSeason();
        return activeSeasonData.id;
    };

    const fetchSeasons = async () => {
        const seasonList = await open_fpl_backend.getSeasons();
        setSeasons(seasonList); 
    };

    const shouldHideColumn = (column) => { 
        return column === 'W' || column === 'D' || column === 'L' || column === 'GF' || column === 'GA';
    };

    const updateTableData = () => {
        const initTeamData = (teamId, table) => {
            if (!table[teamId]) {
                table[teamId] = {
                    teamId,
                    played: 0,
                    wins: 0,
                    draws: 0,
                    losses: 0,
                    goalsFor: 0,
                    goalsAgainst: 0,
                    points: 0
                };
            }
        };
    
        let tempTable = {};
    
        const relevantFixtures = fixtures.filter(fixture => 
            fixture.status === 3 && fixture.gameweek <= selectedGameweek);
    
        for (let fixture of relevantFixtures) {
            initTeamData(fixture.homeTeamId, tempTable);
            initTeamData(fixture.awayTeamId, tempTable);
            tempTable[fixture.homeTeamId].id = fixture.homeTeamId;
            tempTable[fixture.awayTeamId].id = fixture.awayTeamId;
    
            tempTable[fixture.homeTeamId].played++;
            tempTable[fixture.awayTeamId].played++;
    
            tempTable[fixture.homeTeamId].goalsFor += fixture.homeGoals;
            tempTable[fixture.homeTeamId].goalsAgainst += fixture.awayGoals;
            
            tempTable[fixture.awayTeamId].goalsFor += fixture.awayGoals;
            tempTable[fixture.awayTeamId].goalsAgainst += fixture.homeGoals;
    
            if (fixture.homeGoals > fixture.awayGoals) {
                tempTable[fixture.homeTeamId].wins++;
                tempTable[fixture.homeTeamId].points += 3;
    
                tempTable[fixture.awayTeamId].losses++;
            } else if (fixture.homeGoals === fixture.awayGoals) {
                tempTable[fixture.homeTeamId].draws++;
                tempTable[fixture.homeTeamId].points += 1;
    
                tempTable[fixture.awayTeamId].draws++;
                tempTable[fixture.awayTeamId].points += 1;
            } else {
                tempTable[fixture.awayTeamId].wins++;
                tempTable[fixture.awayTeamId].points += 3;
    
                tempTable[fixture.homeTeamId].losses++;
            }
        }
    
        const sortedTableData = Object.values(tempTable).sort((a, b) => {
            if (b.points !== a.points) return b.points - a.points;

            const goalDiffA = a.goalsFor - a.goalsAgainst;
            const goalDiffB = b.goalsFor - b.goalsAgainst;

            if (goalDiffB !== goalDiffA) return goalDiffB - goalDiffA;
            if (b.goalsFor !== a.goalsFor) return b.goalsFor - a.goalsFor;

            return a.goalsAgainst - b.goalsAgainst;
        });
    
        setTableData(sortedTableData);
    };

    const getTeamNameFromId = (teamId) => {
      const team = teams.find(team => team.id === teamId);
      if(!team){
        return;
      }
      return team.friendlyName;
    }

    const columnToBootstrapClasses = (column) => {
        switch (column) {
            case 'Pos':
                return 'col-2 col-md-1';
            case 'Team':
                return 'col-4 col-md-3';
            case 'P':
                return 'col-2 col-md-1';
            case 'W':
                return 'col-0 col-md-1';
            case 'D':
                return 'col-0 col-md-1';
            case 'L':
                return 'col-0 col-md-1';
            case 'GF':
                return 'col-0 col-md-1';
            case 'GA':
                return 'col-0 col-md-1';
            case 'GD':
                return 'col-2 col-md-1';
            case 'Pts':
                return 'col-2 col-md-1';
            default:
                return 'col';
        }
    };
    

    return (
        isLoading ? (
        <div className="customOverlay d-flex flex-column align-items-center justify-content-center">
            <Spinner animation="border" />
            <p className='text-center mt-1'>Loading</p>
        </div>
        ) 
        :
        <Container>
            <Card className='mb-2 mt-4'>
                <Card.Body>
                    <Card.Title className='mb-2'>
                        Premier League Table
                    </Card.Title>
                    <Row className='mb-2 mt-2'>
                        <Col xs={12} md={6} className='mt-2'>
                            <Form.Group controlId="seasonSelect">
                                <Form.Label>Select Season</Form.Label>
                                <Form.Control as="select" value={selectedSeason} onChange={e => {
                                    setSelectedSeason(Number(e.target.value));
                                    setSelectedGameweek(1);
                                }}>
                                    {seasons.map(season => <option key={season.id} value={season.id}>{`${season.name}`}</option>)}
                                </Form.Control>
                            </Form.Group>
                        </Col>
                        <Col xs={12} md={6} className='mt-2'>
                            <Form.Group controlId="gameweekSelect">
                                <Form.Label>Select Gameweek</Form.Label>
                                <Form.Control as="select" value={selectedGameweek} onChange={e => setSelectedGameweek(Number(e.target.value))}>
                                    {Array.from({ length: 38 }, (_, index) => (
                                        <option key={index + 1} value={index + 1}>Gameweek {index + 1}</option>
                                    ))}
                                </Form.Control>
                            </Form.Group>
                        </Col>
                    </Row>

                    <Container>
                        <Row>
                            {activeColumns.map(column => (
                                <Col key={column} className={`${columnToBootstrapClasses(column)} ${shouldHideColumn(column) ? "d-none d-sm-block" : ""}`}>{column}</Col>
                            ))}
                        </Row>
                        {tableData.map((team, idx) => (
                            <Row key={`id-${idx}`}>
                                <Col className={`${columnToBootstrapClasses('Pos')} ${shouldHideColumn('Pos') ? "d-none d-sm-block" : ""}`}>{idx + 1}</Col>
                                <Col className={`${columnToBootstrapClasses('Team')} ${shouldHideColumn('Team') ? "d-none d-sm-block" : ""}`}><LinkContainer to={`/club/${team.id}`}><a className='nav-link-brand'>{getTeamNameFromId(team.teamId)}</a></LinkContainer></Col>
                                <Col className={`${columnToBootstrapClasses('P')} ${shouldHideColumn('P') ? "d-none d-sm-block" : ""}`}>{team.played}</Col>
                                <Col className={`${columnToBootstrapClasses('W')} ${shouldHideColumn('W') ? "d-none d-sm-block" : ""}`}>{team.wins}</Col>
                                <Col className={`${columnToBootstrapClasses('D')} ${shouldHideColumn('D') ? "d-none d-sm-block" : ""}`}>{team.draws}</Col>
                                <Col className={`${columnToBootstrapClasses('L')} ${shouldHideColumn('L') ? "d-none d-sm-block" : ""}`}>{team.losses}</Col>
                                <Col className={`${columnToBootstrapClasses('GF')} ${shouldHideColumn('GF') ? "d-none d-sm-block" : ""}`}>{team.goalsFor}</Col>
                                <Col className={`${columnToBootstrapClasses('GA')} ${shouldHideColumn('GA') ? "d-none d-sm-block" : ""}`}>{team.goalsAgainst}</Col>
                                <Col className={`${columnToBootstrapClasses('GD')} ${shouldHideColumn('GD') ? "d-none d-sm-block" : ""}`}>{team.goalsFor - team.goalsAgainst}</Col>
                                <Col className={`${columnToBootstrapClasses('Pts')} ${shouldHideColumn('Pts') ? "d-none d-sm-block" : ""}`}>{team.points}</Col>
                            </Row>
                        ))}
                    </Container>

                </Card.Body>
            </Card>
             
        </Container>
    );
};

export default LeagueTable;
